### ISSUE TITLE
Error using library in Spring Boot 2.6.2 project "java.lang.NoClassDefFoundError: jakarta/websocket/DeploymentException"

### ISSUE THREAD

**Issue by brunoaduarte** [Auties00/WhatsappWeb4j#105]
```

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.2)

2022-01-11 01:32:03.834  INFO 44036 --- [           main] com.test.wsclient.WsclientMvnApplication  : Starting WsclientMvnApplication using Java 17.0.1 on DESKTOP-M with PID 44036 (C:\Users\Windows\Documents\workspace-spring-tool-suite\wsclient-mvn\target\classes started by Myself in C:\Users\Myself\Documents\workspace-spring-tool-suite\wsclient-mvn)
2022-01-11 01:32:03.836  INFO 44036 --- [           main] com.test.wsclient.WsclientMvnApplication  : No active profile set, falling back to default profiles: default
2022-01-11 01:32:05.618  INFO 44036 --- [           main] com.test.wsclient.WsclientMvnApplication  : Started WsclientMvnApplication in 2.185 seconds (JVM running for 2.524)
2022-01-11 01:32:05.625  INFO 44036 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-01-11 01:32:05.641 ERROR 44036 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.NoClassDefFoundError: jakarta/websocket/DeploymentException
	at it.auties.whatsapp.api.Whatsapp.<init>(Whatsapp.java:50) ~[classes/:na]
	at com.test.wsclient.WsClientRunner.run(WsClientRunner.java:86) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:767) ~[spring-boot-2.6.2.jar:2.6.2]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:751) ~[spring-boot-2.6.2.jar:2.6.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:309) ~[spring-boot-2.6.2.jar:2.6.2]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164) ~[spring-boot-2.6.2.jar:2.6.2]
	at com.test.wsclient.WsclientMvnApplication.main(WsclientMvnApplication.java:22) ~[classes/:na]
Caused by: java.lang.ClassNotFoundException: jakarta.websocket.DeploymentException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 7 common frames omitted

```

Then I add jakarta.websocket to my project's pom.xml

```
		<dependency>
		    <groupId>jakarta.websocket</groupId>
		    <artifactId>jakarta.websocket-api</artifactId>
		    <version>2.0.0</version><!--$NO-MVN-MAN-VER$-->
		    <scope>provided</scope>
		</dependency>
```

And new error appears

```

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.2)

2022-01-11 01:23:12.860  INFO 38520 --- [           main] com.test.wsclient.WsclientMvnApplication  : Starting WsclientMvnApplication using Java 17.0.1 on DESKTOP-M with PID 38520 (C:\Users\Windows\Documents\workspace-spring-tool-suite\wsclient-mvn\target\classes started by Myself in C:\Users\Myself\Documents\workspace-spring-tool-suite\wsclient-mvn)
2022-01-11 01:23:12.862  INFO 38520 --- [           main] com.test.wsclient.WsclientMvnApplication  : No active profile set, falling back to default profiles: default
2022-01-11 01:23:14.645  INFO 38520 --- [           main] com.test.wsclient.WsclientMvnApplication  : Started WsclientMvnApplication in 2.179 seconds (JVM running for 2.534)
java.lang.ExceptionInInitializerError
	at it.auties.whatsapp.socket.WhatsappSocket.onOpen(WhatsappSocket.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.onOpen(AnnotatedEndpoint.java:603)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onConnect(TyrusEndpointWrapper.java:750)
	at org.glassfish.tyrus.core.TyrusWebSocket.onConnect(TyrusWebSocket.java:139)
	at org.glassfish.tyrus.client.TyrusClientEngine.processUpgradeResponse(TyrusClientEngine.java:555)
	at org.glassfish.tyrus.client.TyrusClientEngine.handleSwitchProtocol(TyrusClientEngine.java:318)
	at org.glassfish.tyrus.client.TyrusClientEngine.processResponse(TyrusClientEngine.java:255)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleHandshake(GrizzlyClientFilter.java:322)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:291)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:248)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:181)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:121)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:99)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: buffer is marked non-null but is null
	at it.auties.whatsapp.binary.BinaryEncoder.<init>(BinaryEncoder.java:15)
	at it.auties.whatsapp.binary.BinaryEncoder.<init>(BinaryEncoder.java:21)
	at it.auties.whatsapp.exchange.Request.<clinit>(Request.java:28)
	... 28 more

```

**Comment by EliyahuStern** [comment]
@brunoaduarte why did you close this? Did you find a resolution? 
Please share, It may be helpful to others.

**Comment by GDB4J** [comment]
Note:
Spring boot (tested with version 2.6.6 of springboot ) only works with jakarta.websocket-api version 2.0.0.

Whatsappweb4J does not work with (current) latest version 2.1.0 of jakarta.websocket-api

```
<dependency>
            <groupId>jakarta.websocket</groupId>
            <artifactId>jakarta.websocket-api</artifactId>
            <version>2.0.0</version>
</dependency>
```
