### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: jakarta/websocket/DeploymentException

### ISSUE THREAD

**Issue by ganeshappentus** [Auties00/WhatsappWeb4j#111]
trying to implement with spring boot 
getting this issues

```
Exception in thread "main" java.lang.NoClassDefFoundError: jakarta/websocket/DeploymentException
	at it.auties.whatsapp4j.whatsapp.WhatsappAPI.<init>(WhatsappAPI.java:90)
	at it.auties.whatsapp4j.whatsapp.WhatsappAPI.<init>(WhatsappAPI.java:69)
	at it.auties.whatsapp4j.whatsapp.WhatsappAPI.<init>(WhatsappAPI.java:60)
	at com.example.demo.DemoApplication.main(DemoApplication.java:15)
Caused by: java.lang.ClassNotFoundException: jakarta.websocket.DeploymentException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 4 more
```

**Comment by ganeshappentus** [comment]
@Auties00 can you help me out with this. ?

**Comment by GDB4J** [comment]
More about Spring Boot and WhatsappWeb4j can be found in this issue:
https://github.com/Auties00/WhatsappWeb4j/issues/105

(Also the solution for this problem)
