### ISSUE TITLE
Cannot decrypt message: no suitable session found

### ISSUE THREAD

**Issue by ZiemlichUndead** [Auties00/WhatsappWeb4j#137]
Hi,

I am on RC2 version of W4J and i'm getting following error everytime I write a message from any other device my account is linked to (Same account that the bot is running on):

Juni 17, 2022 4:26:34 PM it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure
WARNUNG: Received status code 400 at MESSAGE(NoSuchElementException: Cannot decrypt message: no suitable session found): handling failure
java.util.NoSuchElementException: Cannot decrypt message: no suitable session found
	at it.auties.whatsapp.crypto.SessionCipher.lambda$decrypt$7(SessionCipher.java:150)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at it.auties.whatsapp.crypto.SessionCipher.lambda$decrypt$8(SessionCipher.java:150)
	at it.auties.whatsapp.util.CipherScheduler.run(CipherScheduler.java:23)
	at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:143)
	at it.auties.whatsapp.binary.BinarySocket$MessageHandler.decodeCipheredMessage(BinarySocket.java:1252)
	at it.auties.whatsapp.binary.BinarySocket$MessageHandler.decodeMessage(BinarySocket.java:1200)
	at it.auties.whatsapp.binary.BinarySocket$MessageHandler.lambda$decode$35(BinarySocket.java:1192)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.binary.BinarySocket$MessageHandler.decode(BinarySocket.java:1192)
	at it.auties.whatsapp.binary.BinarySocket$StreamHandler.digestMessage(BinarySocket.java:527)
	at it.auties.whatsapp.binary.BinarySocket$StreamHandler.digest(BinarySocket.java:514)
	at it.auties.whatsapp.binary.BinarySocket.handleNode(BinarySocket.java:206)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.binary.BinarySocket.onBinary(BinarySocket.java:201)
	at jdk.internal.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553)
	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652)
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:560)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:800)
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
	at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)

After this error the chat that message was sent to seems to break and W4J will now produce the same error everytime a message is sent even when it is sent by the contact. The messages are also not received by WhatsappListener anymore.

This also persists when restarting W4J as long as the session is not deleted.

**Comment by Auties00** [comment]
Yeah this is a known issue, I'm working in it

**Comment by Auties00** [comment]
Should be fixed in version 3.0-RC5. Please let me know
