### ISSUE TITLE
Socket failure at APP_STATE_SYNC (RC7)

### ISSUE THREAD

**Issue by tomlux** [Auties00/WhatsappWeb4j#140]
```
> juin 21, 2022 4:04:51 PM it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure
> WARNING: Socket failure at APP_STATE_SYNC(java.lang.RuntimeException: Cannot parse patch)
> juin 21, 2022 4:04:51 PM it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure
> WARNING: Saved stacktrace at: C:\Users\test\.whatsappweb4j\exceptions\1655820291295.txt
> juin 21, 2022 4:04:51 PM it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure
> WARNING: Restoring session
```
[1655820291295.txt](https://github.com/Auties00/WhatsappWeb4j/files/8949636/1655820291295.txt)

On first run (RC7)

**Comment by tomlux** [comment]
works with RC8 :-)

Now, I'm getting this error:
`
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "it.auties.whatsapp.model.chat.ChatEphemeralTimer.period()" because "this.ephemeralMessageDuration" is null
	at it.auties.whatsappweb4j/it.auties.whatsapp.model.chat.Chat.ephemeralMessageDuration(Chat.java:338)
	at it.auties.whatsappweb4j/it.auties.whatsapp.model.chat.Chat.toString(Chat.java:37)
	at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453)
	at java.base/java.lang.StringConcatHelper.simpleConcat(StringConcatHelper.java:408)
	at it.auties.whatsappweb4j/lu.Test.check(Test.java:33)
	at it.auties.whatsappweb4j/lu.Test.main(Test.java:17)
`
Any idea?

**Comment by tomlux** [comment]
seem to be fixed with:

public Optional<ZonedDateTime> ephemeralMessageDuration() {
   **if(ephemeralMessageDuration==null) return Optional.empty();**
        return Clock.parse(ephemeralMessageDuration.period()
                .toSeconds());
}

**Comment by Auties00** [comment]
> works with RC8 :-)
> 
> Now, I'm getting this error: `Exception in thread "main" java.lang.NullPointerException: Cannot invoke "it.auties.whatsapp.model.chat.ChatEphemeralTimer.period()" because "this.ephemeralMessageDuration" is null at it.auties.whatsappweb4j/it.auties.whatsapp.model.chat.Chat.ephemeralMessageDuration(Chat.java:338) at it.auties.whatsappweb4j/it.auties.whatsapp.model.chat.Chat.toString(Chat.java:37) at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453) at java.base/java.lang.StringConcatHelper.simpleConcat(StringConcatHelper.java:408) at it.auties.whatsappweb4j/lu.Test.check(Test.java:33) at it.auties.whatsappweb4j/lu.Test.main(Test.java:17)` Any idea?

Fixed in RC10, but maven central takes some time to update

**Comment by tomlux** [comment]
works 👍
