### ISSUE TITLE
GroupMetadata:  Missing founder

### ISSUE THREAD

**Issue by tomlux** [Auties00/WhatsappWeb4j#141]
I'm getting this error on a GroupMetadata, it seems that it has no founder information
running RC8

> Caused by: java.util.NoSuchElementException: Missing founder
	at it.auties.whatsappweb4j/it.auties.whatsapp.model.chat.GroupMetadata.lambda$of$2(GroupMetadata.java:58)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at it.auties.whatsappweb4j/it.auties.whatsapp.model.chat.GroupMetadata.of(GroupMetadata.java:58)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by Auties00** [comment]
> I'm getting this error on a GroupMetadata, it seems that it has no founder information running RC8
> 
> > Caused by: java.util.NoSuchElementException: Missing founder
> > at it.auties.whatsappweb4j/it.auties.whatsapp.model.chat.GroupMetadata.lambda$of$2(GroupMetadata.java:58)
> > at java.base/java.util.Optional.orElseThrow(Optional.java:403)
> > at it.auties.whatsappweb4j/it.auties.whatsapp.model.chat.GroupMetadata.of(GroupMetadata.java:58)
> > at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
> > at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
> > at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
> > at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
> > at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
> > at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
> > at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
> > at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

Fixed in RC10, but maven central takes some time to update

**Comment by tomlux** [comment]
works 👍
