### ISSUE TITLE
Image sending seems to have broken

### ISSUE THREAD

**Issue by shmezi** [Auties00/WhatsappWeb4j#147]
Not sure if this is the stack trace for the issue, sorry if it isnt I got no errors when trying to send image only next boot..
```kt
Code for image sending
val i = ImageMessage.newImageMessage()
            .storeId(api.store().id())
            .media(image)
            .caption("test")
            .create()
        api.sendMessage(chat, i)

```
Exception:
```java.util.NoSuchElementException: Cannot decrypt message: no suitable session found
	at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:146)
	at it.auties.whatsapp.binary.Socket$MessageHandler.decode(Socket.java:1359)
	at it.auties.whatsapp.binary.Socket$MessageHandler.decode(Socket.java:1305)
	at it.auties.whatsapp.binary.Socket$MessageHandler.lambda$decode$34(Socket.java:1254)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.binary.Socket$MessageHandler.decode(Socket.java:1254)
	at it.auties.whatsapp.binary.Socket$StreamHandler.digest(Socket.java:547)
	at it.auties.whatsapp.binary.Socket.handleNode(Socket.java:197)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.binary.Socket.onBinary(Socket.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553)
	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652)
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:560)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:800)
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
	at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Key used already or never filled
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor40.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at it.auties.whatsapp.util.Validate.createThrowable(Validate.java:29)
	at it.auties.whatsapp.util.Validate.isTrue(Validate.java:14)
	at it.auties.whatsapp.util.Validate.isTrue(Validate.java:9)
	at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:166)
	at it.auties.whatsapp.crypto.SessionCipher.tryDecrypt(SessionCipher.java:152)
	at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:131)
	... 39 more
```

**Comment by Auties00** [comment]
> @Auties00 Im just using the event listener for message received..

Yeah I've found the issue, i don't rember if I pushed it. If not I will this evening

**Comment by shmezi** [comment]
@Auties00 what was the issue ?

**Comment by Auties00** [comment]
> @Auties00 what was the issue ?

I set the context info to be non-null everywhere but the media builder used as a default value null for context info instead of an empty one

**Comment by shmezi** [comment]
@Auties00 so is it fixed?

**Comment by Auties00** [comment]
> @Auties00 so is it fixed?

I've pushed a temp latest version with the fix

**Comment by shmezi** [comment]
@Auties00



Also I am on RC13

**Comment by Auties00** [comment]
> @Auties00
> 
> Also I am on RC13

Can i see the error marked as MEDIA_CONNECTION?

**Comment by shmezi** [comment]
> > @Auties00
> > Also I am on RC13
> 
> Can i see the error marked as MEDIA_CONNECTION?

```java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "it.auties.whatsapp.model.signal.session.SessionState.remoteIdentityKey()" because "currentState" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NullPointerException: Cannot invoke "it.auties.whatsapp.model.signal.session.SessionState.remoteIdentityKey()" because "currentState" is null
	at it.auties.whatsapp.crypto.SessionCipher.encrypt(SessionCipher.java:30)
	at it.auties.whatsapp.binary.Socket$MessageHandler.createMessageNode(Socket.java:1130)
	at it.auties.whatsapp.binary.Socket$MessageHandler.lambda$createMessageNodes$16(Socket.java:1124)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at it.auties.whatsapp.binary.Socket$MessageHandler.createMessageNodes(Socket.java:1125)
	at it.auties.whatsapp.binary.Socket$MessageHandler.lambda$createConversationNodes$8(Socket.java:1076)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 6 more
``` this one ?
