### ISSUE TITLE
App state writes are broken

### ISSUE THREAD

**Issue by GDB4J** [Auties00/WhatsappWeb4j#152]
Hi @Auties00 
When I'm logging in for the first time (scanning the QRCode), I'm getting this warning/error below

```
ErrorHandler | Socket failure at APP_STATE_SYNC
ErrorHandler | Saved stacktrace at: C:\Users\Geert\.whatsappweb4j\exceptions\1656571592590.txt
ErrorHandler | Ignoring failure
```

Stacktrace of "1656571592590.txt":
```
java.util.concurrent.CompletionException: java.lang.RuntimeException: Cannot parse patch
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.RuntimeException: Cannot parse patch
	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1728)
	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1731)
	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1731)
	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1731)
	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1731)
	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1731)
	at it.auties.whatsapp.binary.Socket$AppStateHandler.lambda$parsePatches$9(Socket.java:1703)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatches(Socket.java:1705)
	at it.auties.whatsapp.binary.Socket$AppStateHandler.handleSyncRequest(Socket.java:1672)
	at it.auties.whatsapp.binary.Socket$AppStateHandler.lambda$pull$7(Socket.java:1666)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 7 more
Caused by: java.lang.IllegalArgumentException: No previous operation for ThC224NbApHvBMuXS/79nMeYYj/6l2wJEhuHTLfrGIE=
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor41.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at it.auties.whatsapp.util.Validate.createThrowable(Validate.java:29)
	at it.auties.whatsapp.util.Validate.isTrue(Validate.java:14)
	at it.auties.whatsapp.util.Validate.isTrue(Validate.java:9)
	at it.auties.whatsapp.crypto.LTHash.mix(LTHash.java:44)
	at it.auties.whatsapp.binary.Socket$AppStateHandler.decodeMutation(Socket.java:2016)
	at it.auties.whatsapp.binary.Socket$AppStateHandler.lambda$decodeMutations$33(Socket.java:1992)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at it.auties.whatsapp.binary.Socket$AppStateHandler.decodeMutations(Socket.java:1993)
	at it.auties.whatsapp.binary.Socket$AppStateHandler.decodePatch(Socket.java:1927)
	at it.auties.whatsapp.binary.Socket$AppStateHandler.lambda$decodePatches$27(Socket.java:1906)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at it.auties.whatsapp.binary.Socket$AppStateHandler.decodePatches(Socket.java:1908)
	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1718)
	... 21 more
```

But everythings seems to work fine

Tested on version
` <version>3.0-RC13</version>`

Can i fix this somehow?

Thanks in advance,
Kind regards

**Comment by Auties00** [comment]
> Hi @Auties00 When I'm logging in for the first time (scanning the QRCode), I'm getting this warning/error below
> 
> ```
> ErrorHandler | Socket failure at APP_STATE_SYNC
> ErrorHandler | Saved stacktrace at: C:\Users\Geert\.whatsappweb4j\exceptions\1656571592590.txt
> ErrorHandler | Ignoring failure
> ```
> 
> Stacktrace of "1656571592590.txt":
> 
> ```
> java.util.concurrent.CompletionException: java.lang.RuntimeException: Cannot parse patch
> 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
> 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
> 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
> 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
> Caused by: java.lang.RuntimeException: Cannot parse patch
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1728)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1731)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1731)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1731)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1731)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1731)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.lambda$parsePatches$9(Socket.java:1703)
> 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
> 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
> 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
> 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
> 	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatches(Socket.java:1705)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.handleSyncRequest(Socket.java:1672)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.lambda$pull$7(Socket.java:1666)
> 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
> 	... 7 more
> Caused by: java.lang.IllegalArgumentException: No previous operation for ThC224NbApHvBMuXS/79nMeYYj/6l2wJEhuHTLfrGIE=
> 	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor41.newInstance(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
> 	at it.auties.whatsapp.util.Validate.createThrowable(Validate.java:29)
> 	at it.auties.whatsapp.util.Validate.isTrue(Validate.java:14)
> 	at it.auties.whatsapp.util.Validate.isTrue(Validate.java:9)
> 	at it.auties.whatsapp.crypto.LTHash.mix(LTHash.java:44)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.decodeMutation(Socket.java:2016)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.lambda$decodeMutations$33(Socket.java:1992)
> 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> 	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.decodeMutations(Socket.java:1993)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.decodePatch(Socket.java:1927)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.lambda$decodePatches$27(Socket.java:1906)
> 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
> 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
> 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
> 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
> 	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.decodePatches(Socket.java:1908)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1718)
> 	... 21 more
> ```
> 
> But everythings seems to work fine
> 
> Tested on version ` <version>3.0-RC13</version>`
> 
> Can i fix this somehow?
> 
> Thanks in advance, Kind regards



> Hi @Auties00 When I'm logging in for the first time (scanning the QRCode), I'm getting this warning/error below
> 
> ```
> ErrorHandler | Socket failure at APP_STATE_SYNC
> ErrorHandler | Saved stacktrace at: C:\Users\Geert\.whatsappweb4j\exceptions\1656571592590.txt
> ErrorHandler | Ignoring failure
> ```
> 
> Stacktrace of "1656571592590.txt":
> 
> ```
> java.util.concurrent.CompletionException: java.lang.RuntimeException: Cannot parse patch
> 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
> 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
> 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
> 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
> Caused by: java.lang.RuntimeException: Cannot parse patch
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1728)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1731)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1731)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1731)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1731)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1731)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.lambda$parsePatches$9(Socket.java:1703)
> 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
> 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
> 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
> 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
> 	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatches(Socket.java:1705)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.handleSyncRequest(Socket.java:1672)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.lambda$pull$7(Socket.java:1666)
> 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
> 	... 7 more
> Caused by: java.lang.IllegalArgumentException: No previous operation for ThC224NbApHvBMuXS/79nMeYYj/6l2wJEhuHTLfrGIE=
> 	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor41.newInstance(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
> 	at it.auties.whatsapp.util.Validate.createThrowable(Validate.java:29)
> 	at it.auties.whatsapp.util.Validate.isTrue(Validate.java:14)
> 	at it.auties.whatsapp.util.Validate.isTrue(Validate.java:9)
> 	at it.auties.whatsapp.crypto.LTHash.mix(LTHash.java:44)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.decodeMutation(Socket.java:2016)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.lambda$decodeMutations$33(Socket.java:1992)
> 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> 	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.decodeMutations(Socket.java:1993)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.decodePatch(Socket.java:1927)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.lambda$decodePatches$27(Socket.java:1906)
> 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
> 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
> 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
> 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
> 	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.decodePatches(Socket.java:1908)
> 	at it.auties.whatsapp.binary.Socket$AppStateHandler.parsePatch(Socket.java:1718)
> 	... 21 more
> ```
> 
> But everythings seems to work fine
> 
> Tested on version ` <version>3.0-RC13</version>`
> 
> Can i fix this somehow?
> 
> Thanks in advance, Kind regards

As I was saying in a previous issue, this release has a bug with app state writes. In short archiving, pinning and marking chats as read doesn't work and throws that exception. I'm working on a fix

**Comment by Auties00** [comment]
Fixed in latest commit, check version RC14
