### ISSUE TITLE
Generating link preview failes for gmail adresses which prevents message from sending

### ISSUE THREAD

**Issue by ZiemlichUndead** [Auties00/WhatsappWeb4j#167]
(RC18)
I just noticed that I cannot send a message with WhatsappWeb4j containing (valid) gmail adresses.
I get the following error:
SCHWERWIEGEND: Ignored failure
java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getType()" because "originalImage" is null
	at it.auties.whatsapp.util.Medias.getResizedImage(Medias.java:334)
	at it.auties.whatsapp.util.Medias.getImage(Medias.java:307)
	at it.auties.whatsapp.util.Medias.getPreview(Medias.java:60)
	at it.auties.whatsapp.api.Whatsapp.createTextPreview(Whatsapp.java:953)
	at it.auties.whatsapp.api.Whatsapp.sendMessage(Whatsapp.java:919)
	at it.auties.whatsapp.api.Whatsapp.sendMessage(Whatsapp.java:900)
	at it.auties.whatsapp.api.Whatsapp.sendMessage(Whatsapp.java:814)
	at de.qua_events.chatbot.wapi.bot.APIHandler.sendMessage(APIHandler.java:111)
	at de.qua_events.chatbot.ChatBot.sendMessage(ChatBot.java:248)
	at de.qua_events.chatbot.alerting.AlertHandler.sendAlert(AlertHandler.java:10)
	at de.qua_events.chatbot.chats.CourseChat.sendAndValidateMail(CourseChat.java:252)
	at de.qua_events.chatbot.chats.CourseChat.chatExecutor(CourseChat.java:36)
	at de.qua_events.chatbot.chats.Chat.lambda$start$0(Chat.java:36)
	at java.base/java.lang.Thread.run(Thread.java:833)

It seems to me that in case of gmail adresses WhatsappWeb4j tries to resolve some sort of link preview from google. I know that i have been able to send messages containing gmail adresses in the past but I don't know which version I was on then.

**Comment by Auties00** [comment]
> (RC18) I just noticed that I cannot send a message with WhatsappWeb4j containing (valid) gmail adresses. I get the following error: SCHWERWIEGEND: Ignored failure java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getType()" because "originalImage" is null at it.auties.whatsapp.util.Medias.getResizedImage(Medias.java:334) at it.auties.whatsapp.util.Medias.getImage(Medias.java:307) at it.auties.whatsapp.util.Medias.getPreview(Medias.java:60) at it.auties.whatsapp.api.Whatsapp.createTextPreview(Whatsapp.java:953) at it.auties.whatsapp.api.Whatsapp.sendMessage(Whatsapp.java:919) at it.auties.whatsapp.api.Whatsapp.sendMessage(Whatsapp.java:900) at it.auties.whatsapp.api.Whatsapp.sendMessage(Whatsapp.java:814) at de.qua_events.chatbot.wapi.bot.APIHandler.sendMessage(APIHandler.java:111) at de.qua_events.chatbot.ChatBot.sendMessage(ChatBot.java:248) at de.qua_events.chatbot.alerting.AlertHandler.sendAlert(AlertHandler.java:10) at de.qua_events.chatbot.chats.CourseChat.sendAndValidateMail(CourseChat.java:252) at de.qua_events.chatbot.chats.CourseChat.chatExecutor(CourseChat.java:36) at de.qua_events.chatbot.chats.Chat.lambda$start$0(Chat.java:36) at java.base/java.lang.Thread.run(Thread.java:833)
> 
> It seems to me that in case of gmail adresses WhatsappWeb4j tries to resolve some sort of link preview from google. I know that i have been able to send messages containing gmail adresses in the past but I don't know which version I was on then.

Yeah it's a new feature, go in the options and disable automatic link preview while I work on a fix. I'm on vacation rn

**Comment by Auties00** [comment]
> getPreview

Fixed in the latest version(i'll push in max an hour)
