### ISSUE TITLE
Whatsapp business:(V 3.0-RC26) When scanning QR I get the following error: 

### ISSUE THREAD

**Issue by diegoalbertosaez** [Auties00/WhatsappWeb4j#181]
SEVERE: Socket failure at MESSAGE
java.lang.reflect.InvocationTargetException
  at jdk.internal.reflect.GeneratedMethodAccessor219.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at it.auties.protobuf.api.jackson.ProtobufParser.readDelimitedWithConversion(ProtobufParser.java:252)
  at it.auties.protobuf.api.jackson.ProtobufParser.readNextToken(ProtobufParser.java:212)
  at it.auties.protobuf.api.jackson.ProtobufParser.nextToken(ProtobufParser.java:161)
  at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:289)
  at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217)
  at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
  at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4650)
  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2831)
  at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:2277)
  at it.auties.protobuf.api.jackson.ProtobufParser.readEmbeddedMessage(ProtobufParser.java:308)
  at it.auties.protobuf.api.jackson.ProtobufParser.readDelimited(ProtobufParser.java:274)
  at it.auties.protobuf.api.jackson.ProtobufParser.readDelimitedWithConversion(ProtobufParser.java:243)
  at it.auties.protobuf.api.jackson.ProtobufParser.readNextToken(ProtobufParser.java:212)
  at it.auties.protobuf.api.jackson.ProtobufParser.nextToken(ProtobufParser.java:161)
  at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:289)
  at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217)
  at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
  at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2051)
  at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1529)
  at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1544)
  at it.auties.protobuf.api.jackson.ProtobufMapper.readMessage(ProtobufMapper.java:35)
  at it.auties.whatsapp.socket.MessageHandler.handleProtocolMessage(MessageHandler.java:545)
  at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:434)
  at it.auties.whatsapp.socket.MessageHandler.lambda$decode$36(MessageHandler.java:370)
  at java.base/java.lang.Iterable.forEach(Iterable.java:75)
  at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:370)
  at it.auties.whatsapp.socket.Socket.readMessage(Socket.java:296)
  at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:65)
  at it.auties.whatsapp.socket.Socket.handleNode(Socket.java:186)
  at java.base/java.lang.Iterable.forEach(Iterable.java:75)
  at it.auties.whatsapp.socket.Socket.onBinary(Socket.java:181)
  at jdk.internal.reflect.GeneratedMethodAccessor180.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
  at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
  at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
  at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
  at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
  at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
  at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
  at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
  at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
  at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
  at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
  at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
  at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
  at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
  at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
  at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
  at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
  at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
  at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
  at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
  at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
  at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
  at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
  at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
  at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NumberFormatException: For input string: "me"
  at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
  at java.base/java.lang.Integer.parseInt(Integer.java:668)
  at java.base/java.lang.Integer.parseUnsignedInt(Integer.java:848)
  at java.base/java.lang.Integer.parseUnsignedInt(Integer.java:944)
  at it.auties.whatsapp.model.contact.ContactJid.of(ContactJid.java:90)
  at it.auties.whatsapp.model.contact.ContactJid.of(ContactJid.java:56)
  at it.auties.whatsapp.model.contact.ContactJid.convert(ContactJid.java:152)
  ... 62 more
Sep 20, 2022 8:32:55 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Ignored failure
Caused by: java.lang.NumberFormatException: For input string: "me"

**Comment by Auties00** [comment]
> SEVERE: Socket failure at MESSAGE java.lang.reflect.InvocationTargetException at jdk.internal.reflect.GeneratedMethodAccessor219.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at it.auties.protobuf.api.jackson.ProtobufParser.readDelimitedWithConversion(ProtobufParser.java:252) at it.auties.protobuf.api.jackson.ProtobufParser.readNextToken(ProtobufParser.java:212) at it.auties.protobuf.api.jackson.ProtobufParser.nextToken(ProtobufParser.java:161) at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:289) at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217) at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4650) at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2831) at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:2277) at it.auties.protobuf.api.jackson.ProtobufParser.readEmbeddedMessage(ProtobufParser.java:308) at it.auties.protobuf.api.jackson.ProtobufParser.readDelimited(ProtobufParser.java:274) at it.auties.protobuf.api.jackson.ProtobufParser.readDelimitedWithConversion(ProtobufParser.java:243) at it.auties.protobuf.api.jackson.ProtobufParser.readNextToken(ProtobufParser.java:212) at it.auties.protobuf.api.jackson.ProtobufParser.nextToken(ProtobufParser.java:161) at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:289) at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217) at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2051) at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1529) at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1544) at it.auties.protobuf.api.jackson.ProtobufMapper.readMessage(ProtobufMapper.java:35) at it.auties.whatsapp.socket.MessageHandler.handleProtocolMessage(MessageHandler.java:545) at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:434) at it.auties.whatsapp.socket.MessageHandler.lambda$decode$36(MessageHandler.java:370) at java.base/java.lang.Iterable.forEach(Iterable.java:75) at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:370) at it.auties.whatsapp.socket.Socket.readMessage(Socket.java:296) at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:65) at it.auties.whatsapp.socket.Socket.handleNode(Socket.java:186) at java.base/java.lang.Iterable.forEach(Iterable.java:75) at it.auties.whatsapp.socket.Socket.onBinary(Socket.java:181) at jdk.internal.reflect.GeneratedMethodAccessor180.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556) at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655) at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591) at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806) at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183) at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70) at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819) at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726) at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452) at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91) at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68) at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248) at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88) at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246) at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178) at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118) at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96) at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51) at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510) at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82) at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83) at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101) at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) at java.base/java.lang.Thread.run(Thread.java:833) Caused by: java.lang.NumberFormatException: For input string: "me" at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) at java.base/java.lang.Integer.parseInt(Integer.java:668) at java.base/java.lang.Integer.parseUnsignedInt(Integer.java:848) at java.base/java.lang.Integer.parseUnsignedInt(Integer.java:944) at it.auties.whatsapp.model.contact.ContactJid.of(ContactJid.java:90) at it.auties.whatsapp.model.contact.ContactJid.of(ContactJid.java:56) at it.auties.whatsapp.model.contact.ContactJid.convert(ContactJid.java:152) ... 62 more Sep 20, 2022 8:32:55 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1 SEVERE: Ignored failure Caused by: java.lang.NumberFormatException: For input string: "me"

can you place a breakpoint there to see what's the actual string?

**Comment by diegoalbertosaez** [comment]
The variable **"complexUser"** has the value **"status_me"**. I highlight it on the screenshot.
![Screenshot from 2022-09-21 09-05-58](https://user-images.githubusercontent.com/31957729/191500159-c9cfd2f4-1ea1-48e0-bbe5-a528b2870318.png)

**Comment by Auties00** [comment]
> The variable **"complexUser"** has the value **"status_me"**. I highlight it on the screenshot. ![Screenshot from 2022-09-21 09-05-58](https://user-images.githubusercontent.com/31957729/191500159-c9cfd2f4-1ea1-48e0-bbe5-a528b2870318.png)

Can you show me the args of the function that you are in? Would do it myself but I'm in school sadly:/

**Comment by diegoalbertosaez** [comment]
No problem!
The **jid** parameter has a value of "status_me".
![Screenshot from 2022-09-21 09-05-58](https://user-images.githubusercontent.com/31957729/191515079-06b30d1f-da61-4a59-98ca-702e385d656f.png)

**Comment by Auties00** [comment]
> No problem! The **jid** parameter has a value of "status_me".
> 
> ![Screenshot from 2022-09-21 10-19-38](https://user-images.githubusercontent.com/31957729/191515214-0d7c49f1-5f10-46d9-8f06-d9044d124ece.png)

Can you show me the call stack? I've never seen a jid like that I'm so confused

**Comment by diegoalbertosaez** [comment]
here it goes!

of:90, ContactJid (it.auties.whatsapp.model.contact)
of:56, ContactJid (it.auties.whatsapp.model.contact)
convert:152, ContactJid (it.auties.whatsapp.model.contact)
invoke:-1, GeneratedMethodAccessor163 (jdk.internal.reflect)
invoke:43, DelegatingMethodAccessorImpl (jdk.internal.reflect)
invoke:568, Method (java.lang.reflect)
readDelimitedWithConversion:252, ProtobufParser (it.auties.protobuf.api.jackson)
readNextToken:212, ProtobufParser (it.auties.protobuf.api.jackson)
nextToken:161, ProtobufParser (it.auties.protobuf.api.jackson)
vanillaDeserialize:289, BuilderBasedDeserializer (com.fasterxml.jackson.databind.deser)
deserialize:217, BuilderBasedDeserializer (com.fasterxml.jackson.databind.deser)
readRootValue:323, DefaultDeserializationContext (com.fasterxml.jackson.databind.deser)
_readValue:4650, ObjectMapper (com.fasterxml.jackson.databind)
readValue:2831, ObjectMapper (com.fasterxml.jackson.databind)
readValueAs:2277, JsonParser (com.fasterxml.jackson.core)
readEmbeddedMessage:308, ProtobufParser (it.auties.protobuf.api.jackson)
readDelimited:274, ProtobufParser (it.auties.protobuf.api.jackson)
readDelimitedWithConversion:243, ProtobufParser (it.auties.protobuf.api.jackson)
readNextToken:212, ProtobufParser (it.auties.protobuf.api.jackson)
nextToken:161, ProtobufParser (it.auties.protobuf.api.jackson)
vanillaDeserialize:289, BuilderBasedDeserializer (com.fasterxml.jackson.databind.deser)
deserialize:217, BuilderBasedDeserializer (com.fasterxml.jackson.databind.deser)
readRootValue:323, DefaultDeserializationContext (com.fasterxml.jackson.databind.deser)
_bindAndClose:2051, ObjectReader (com.fasterxml.jackson.databind)
readValue:1529, ObjectReader (com.fasterxml.jackson.databind)
readValue:1544, ObjectReader (com.fasterxml.jackson.databind)
readMessage:35, ProtobufMapper (it.auties.protobuf.api.jackson)
handleProtocolMessage:545, MessageHandler (it.auties.whatsapp.socket)
decode:434, MessageHandler (it.auties.whatsapp.socket)
lambda$decode$36:370, MessageHandler (it.auties.whatsapp.socket)
accept:-1, MessageHandler$$Lambda$279/0x0000000800f1da98 (it.auties.whatsapp.socket)
forEach:75, Iterable (java.lang)
decode:370, MessageHandler (it.auties.whatsapp.socket)
readMessage:296, Socket (it.auties.whatsapp.socket)
digest:65, StreamHandler (it.auties.whatsapp.socket)
handleNode:186, Socket (it.auties.whatsapp.socket)
accept:-1, Socket$$Lambda$192/0x0000000800ee0f10 (it.auties.whatsapp.socket)
forEach:75, Iterable (java.lang)
onBinary:181, Socket (it.auties.whatsapp.socket)
invoke:-1, GeneratedMethodAccessor123 (jdk.internal.reflect)
invoke:43, DelegatingMethodAccessorImpl (jdk.internal.reflect)
invoke:568, Method (java.lang.reflect)
callMethod:556, AnnotatedEndpoint (org.glassfish.tyrus.core)
onMessage:655, AnnotatedEndpoint$WholeHandler$1 (org.glassfish.tyrus.core)
notifyMessageHandlers:591, TyrusSession (org.glassfish.tyrus.core)
onMessage:806, TyrusEndpointWrapper (org.glassfish.tyrus.core)
onMessage:183, TyrusWebSocket (org.glassfish.tyrus.core)
respond:70, BinaryFrame (org.glassfish.tyrus.core.frame)
process:819, ProtocolHandler (org.glassfish.tyrus.core)
handle:726, TyrusClientEngine$TyrusReadHandler (org.glassfish.tyrus.client)
execute:452, GrizzlyClientFilter$ProcessTask (org.glassfish.tyrus.container.grizzly.client)
processTask:91, TaskProcessor (org.glassfish.tyrus.container.grizzly.client)
processTask:68, TaskProcessor (org.glassfish.tyrus.container.grizzly.client)
handleRead:248, GrizzlyClientFilter (org.glassfish.tyrus.container.grizzly.client)
execute:88, ExecutorResolver$9 (org.glassfish.grizzly.filterchain)
executeFilter:246, DefaultFilterChain (org.glassfish.grizzly.filterchain)
executeChainPart:178, DefaultFilterChain (org.glassfish.grizzly.filterchain)
execute:118, DefaultFilterChain (org.glassfish.grizzly.filterchain)
process:96, DefaultFilterChain (org.glassfish.grizzly.filterchain)
execute:51, ProcessorExecutor (org.glassfish.grizzly)
fireIOEvent:510, TCPNIOTransport (org.glassfish.grizzly.nio.transport)
fireIOEvent:82, AbstractIOStrategy (org.glassfish.grizzly.strategies)
run0:83, WorkerThreadIOStrategy (org.glassfish.grizzly.strategies)
run:101, WorkerThreadIOStrategy$WorkerThreadRunnable (org.glassfish.grizzly.strategies)
doWork:535, AbstractThreadPool$Worker (org.glassfish.grizzly.threadpool)
run:515, AbstractThreadPool$Worker (org.glassfish.grizzly.threadpool)
run:833, Thread (java.lang)

**Comment by Auties00** [comment]
> 

I'll fix it as soon as I get home

**Comment by Auties00** [comment]
> here it goes!
> 
> of:90, ContactJid (it.auties.whatsapp.model.contact) of:56, ContactJid (it.auties.whatsapp.model.contact) convert:152, ContactJid (it.auties.whatsapp.model.contact) invoke:-1, GeneratedMethodAccessor163 (jdk.internal.reflect) invoke:43, DelegatingMethodAccessorImpl (jdk.internal.reflect) invoke:568, Method (java.lang.reflect) readDelimitedWithConversion:252, ProtobufParser (it.auties.protobuf.api.jackson) readNextToken:212, ProtobufParser (it.auties.protobuf.api.jackson) nextToken:161, ProtobufParser (it.auties.protobuf.api.jackson) vanillaDeserialize:289, BuilderBasedDeserializer (com.fasterxml.jackson.databind.deser) deserialize:217, BuilderBasedDeserializer (com.fasterxml.jackson.databind.deser) readRootValue:323, DefaultDeserializationContext (com.fasterxml.jackson.databind.deser) _readValue:4650, ObjectMapper (com.fasterxml.jackson.databind) readValue:2831, ObjectMapper (com.fasterxml.jackson.databind) readValueAs:2277, JsonParser (com.fasterxml.jackson.core) readEmbeddedMessage:308, ProtobufParser (it.auties.protobuf.api.jackson) readDelimited:274, ProtobufParser (it.auties.protobuf.api.jackson) readDelimitedWithConversion:243, ProtobufParser (it.auties.protobuf.api.jackson) readNextToken:212, ProtobufParser (it.auties.protobuf.api.jackson) nextToken:161, ProtobufParser (it.auties.protobuf.api.jackson) vanillaDeserialize:289, BuilderBasedDeserializer (com.fasterxml.jackson.databind.deser) deserialize:217, BuilderBasedDeserializer (com.fasterxml.jackson.databind.deser) readRootValue:323, DefaultDeserializationContext (com.fasterxml.jackson.databind.deser) _bindAndClose:2051, ObjectReader (com.fasterxml.jackson.databind) readValue:1529, ObjectReader (com.fasterxml.jackson.databind) readValue:1544, ObjectReader (com.fasterxml.jackson.databind) readMessage:35, ProtobufMapper (it.auties.protobuf.api.jackson) handleProtocolMessage:545, MessageHandler (it.auties.whatsapp.socket) decode:434, MessageHandler (it.auties.whatsapp.socket) lambda$decode$36:370, MessageHandler (it.auties.whatsapp.socket) accept:-1, MessageHandler$$Lambda$279/0x0000000800f1da98 (it.auties.whatsapp.socket) forEach:75, Iterable (java.lang) decode:370, MessageHandler (it.auties.whatsapp.socket) readMessage:296, Socket (it.auties.whatsapp.socket) digest:65, StreamHandler (it.auties.whatsapp.socket) handleNode:186, Socket (it.auties.whatsapp.socket) accept:-1, Socket$$Lambda$192/0x0000000800ee0f10 (it.auties.whatsapp.socket) forEach:75, Iterable (java.lang) onBinary:181, Socket (it.auties.whatsapp.socket) invoke:-1, GeneratedMethodAccessor123 (jdk.internal.reflect) invoke:43, DelegatingMethodAccessorImpl (jdk.internal.reflect) invoke:568, Method (java.lang.reflect) callMethod:556, AnnotatedEndpoint (org.glassfish.tyrus.core) onMessage:655, AnnotatedEndpoint$WholeHandler$1 (org.glassfish.tyrus.core) notifyMessageHandlers:591, TyrusSession (org.glassfish.tyrus.core) onMessage:806, TyrusEndpointWrapper (org.glassfish.tyrus.core) onMessage:183, TyrusWebSocket (org.glassfish.tyrus.core) respond:70, BinaryFrame (org.glassfish.tyrus.core.frame) process:819, ProtocolHandler (org.glassfish.tyrus.core) handle:726, TyrusClientEngine$TyrusReadHandler (org.glassfish.tyrus.client) execute:452, GrizzlyClientFilter$ProcessTask (org.glassfish.tyrus.container.grizzly.client) processTask:91, TaskProcessor (org.glassfish.tyrus.container.grizzly.client) processTask:68, TaskProcessor (org.glassfish.tyrus.container.grizzly.client) handleRead:248, GrizzlyClientFilter (org.glassfish.tyrus.container.grizzly.client) execute:88, ExecutorResolver$9 (org.glassfish.grizzly.filterchain) executeFilter:246, DefaultFilterChain (org.glassfish.grizzly.filterchain) executeChainPart:178, DefaultFilterChain (org.glassfish.grizzly.filterchain) execute:118, DefaultFilterChain (org.glassfish.grizzly.filterchain) process:96, DefaultFilterChain (org.glassfish.grizzly.filterchain) execute:51, ProcessorExecutor (org.glassfish.grizzly) fireIOEvent:510, TCPNIOTransport (org.glassfish.grizzly.nio.transport) fireIOEvent:82, AbstractIOStrategy (org.glassfish.grizzly.strategies) run0:83, WorkerThreadIOStrategy (org.glassfish.grizzly.strategies) run:101, WorkerThreadIOStrategy$WorkerThreadRunnable (org.glassfish.grizzly.strategies) doWork:535, AbstractThreadPool$Worker (org.glassfish.grizzly.threadpool) run:515, AbstractThreadPool$Worker (org.glassfish.grizzly.threadpool) run:833, Thread (java.lang)

So i tried to reproduce this issue but I can't in any way for some reason, sorry for taking so long but I was busy on other issues. Can you please navigate the call stack, go to readEmbeddedMessage and evaluate the type field? Thanks in advance and sorry for the long wait time
