### ISSUE TITLE
Error when sending/receiving message

### ISSUE THREAD

**Issue by xNoobyyy** [Auties00/WhatsappWeb4j#184]
Ok so basically I get this error sometimes directly on startup and everytime I receive a message (or send a message in a chat with my phone). I don't know if the error is on my end or if it's a bug

```
java.lang.RuntimeException: Cannot decrypt message with type pkmsg inside <My Number>:18@s.whatsapp.net from <My Number>:18@s.whatsapp.net
        at it.auties.whatsapp.socket.MessageHandler.decodeMessageBytes(MessageHandler.java:487)
        at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:416)
        at it.auties.whatsapp.socket.MessageHandler.lambda$decode$36(MessageHandler.java:370)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:370)
        at it.auties.whatsapp.socket.Socket.readMessage(Socket.java:296)
        at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:65)
        at it.auties.whatsapp.socket.Socket.handleNode(Socket.java:186)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at it.auties.whatsapp.socket.Socket.onBinary(Socket.java:181)
        at jdk.internal.reflect.GeneratedMethodAccessor202.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
        at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
        at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
        at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
        at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
        at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
        at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
        at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ConcurrentLinkedDeque.stream()" because "this.states" is null
        at it.auties.whatsapp.model.signal.session.Session.hasState(Session.java:30)
        at it.auties.whatsapp.crypto.SessionBuilder.createIncoming(SessionBuilder.java:54)
        at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:117)
        at it.auties.whatsapp.socket.MessageHandler.decodeMessageBytes(MessageHandler.java:467)
        ... 37 more
Oct. 18, 2022 5:26:00 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
FATAL: Ignored failure
Oct. 18, 2022 5:26:00 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
FATAL: Socket failure at MESSAGE
```

**Comment by Auties00** [comment]
> Ok so basically I get this error sometimes directly on startup and everytime I receive a message (or send a message in a chat with my phone). I don't know if the error is on my end or if it's a bug
> 
> ```
> java.lang.RuntimeException: Cannot decrypt message with type pkmsg inside <My Number>:18@s.whatsapp.net from <My Number>:18@s.whatsapp.net
>         at it.auties.whatsapp.socket.MessageHandler.decodeMessageBytes(MessageHandler.java:487)
>         at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:416)
>         at it.auties.whatsapp.socket.MessageHandler.lambda$decode$36(MessageHandler.java:370)
>         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
>         at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:370)
>         at it.auties.whatsapp.socket.Socket.readMessage(Socket.java:296)
>         at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:65)
>         at it.auties.whatsapp.socket.Socket.handleNode(Socket.java:186)
>         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
>         at it.auties.whatsapp.socket.Socket.onBinary(Socket.java:181)
>         at jdk.internal.reflect.GeneratedMethodAccessor202.invoke(Unknown Source)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
>         at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
>         at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
>         at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
>         at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
>         at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
>         at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
>         at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
>         at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
>         at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
>         at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
>         at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
>         at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
>         at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
>         at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
>         at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
>         at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
>         at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
>         at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
>         at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
>         at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
>         at java.base/java.lang.Thread.run(Thread.java:833)
> Caused by: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ConcurrentLinkedDeque.stream()" because "this.states" is null
>         at it.auties.whatsapp.model.signal.session.Session.hasState(Session.java:30)
>         at it.auties.whatsapp.crypto.SessionBuilder.createIncoming(SessionBuilder.java:54)
>         at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:117)
>         at it.auties.whatsapp.socket.MessageHandler.decodeMessageBytes(MessageHandler.java:467)
>         ... 37 more
> Oct. 18, 2022 5:26:00 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
> FATAL: Ignored failure
> Oct. 18, 2022 5:26:00 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
> FATAL: Socket failure at MESSAGE
> ```

Version?

**Comment by xNoobyyy** [comment]
RC26

> > Ok so basically I get this error sometimes directly on startup and everytime I receive a message (or send a message in a chat with my phone). I don't know if the error is on my end or if it's a bug
> > ```
> > java.lang.RuntimeException: Cannot decrypt message with type pkmsg inside <My Number>:18@s.whatsapp.net from <My Number>:18@s.whatsapp.net
> >         at it.auties.whatsapp.socket.MessageHandler.decodeMessageBytes(MessageHandler.java:487)
> >         at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:416)
> >         at it.auties.whatsapp.socket.MessageHandler.lambda$decode$36(MessageHandler.java:370)
> >         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
> >         at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:370)
> >         at it.auties.whatsapp.socket.Socket.readMessage(Socket.java:296)
> >         at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:65)
> >         at it.auties.whatsapp.socket.Socket.handleNode(Socket.java:186)
> >         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
> >         at it.auties.whatsapp.socket.Socket.onBinary(Socket.java:181)
> >         at jdk.internal.reflect.GeneratedMethodAccessor202.invoke(Unknown Source)
> >         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> >         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> >         at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
> >         at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
> >         at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
> >         at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
> >         at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
> >         at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
> >         at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
> >         at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
> >         at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
> >         at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
> >         at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
> >         at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
> >         at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
> >         at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
> >         at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
> >         at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
> >         at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
> >         at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
> >         at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
> >         at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
> >         at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
> >         at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
> >         at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
> >         at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
> >         at java.base/java.lang.Thread.run(Thread.java:833)
> > Caused by: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ConcurrentLinkedDeque.stream()" because "this.states" is null
> >         at it.auties.whatsapp.model.signal.session.Session.hasState(Session.java:30)
> >         at it.auties.whatsapp.crypto.SessionBuilder.createIncoming(SessionBuilder.java:54)
> >         at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:117)
> >         at it.auties.whatsapp.socket.MessageHandler.decodeMessageBytes(MessageHandler.java:467)
> >         ... 37 more
> > Oct. 18, 2022 5:26:00 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
> > FATAL: Ignored failure
> > Oct. 18, 2022 5:26:00 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
> > FATAL: Socket failure at MESSAGE
> > ```
> 
> Version?

RC26 / tried other versions as well

**Comment by xNoobyyy** [comment]
any updates?

also I sometimes get the following error while starting, maybe it has something to do with it?

```
java.lang.RuntimeException: Cannot decrypt message with type msg inside 4917647684504:18@s.whatsapp.net from 4917647684504:18@s.whatsapp.net
	at it.auties.whatsapp.socket.MessageHandler.decodeMessageBytes(MessageHandler.java:487)
	at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:416)
	at it.auties.whatsapp.socket.MessageHandler.lambda$decode$36(MessageHandler.java:370)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:370)
	at it.auties.whatsapp.socket.Socket.readMessage(Socket.java:296)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:65)
	at it.auties.whatsapp.socket.Socket.handleNode(Socket.java:186)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.socket.Socket.onBinary(Socket.java:181)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
	at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.NoSuchElementException: Cannot decrypt message: no suitable session found
	at it.auties.whatsapp.crypto.SessionCipher.lambda$decrypt$5(SessionCipher.java:137)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:137)
	at it.auties.whatsapp.socket.MessageHandler.decodeMessageBytes(MessageHandler.java:479)
	... 38 more
Okt. 22, 2022 9:15:08 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
FATAL: Ignored failure
```

**Comment by xNoobyyy** [comment]
any updates?

also I sometimes get the following error while starting, maybe it has something to do with it?

```
java.lang.RuntimeException: Cannot decrypt message with type msg inside <number>:18@s.whatsapp.net from <number>:18@s.whatsapp.net
	at it.auties.whatsapp.socket.MessageHandler.decodeMessageBytes(MessageHandler.java:487)
	at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:416)
	at it.auties.whatsapp.socket.MessageHandler.lambda$decode$36(MessageHandler.java:370)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:370)
	at it.auties.whatsapp.socket.Socket.readMessage(Socket.java:296)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:65)
	at it.auties.whatsapp.socket.Socket.handleNode(Socket.java:186)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.socket.Socket.onBinary(Socket.java:181)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
	at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.NoSuchElementException: Cannot decrypt message: no suitable session found
	at it.auties.whatsapp.crypto.SessionCipher.lambda$decrypt$5(SessionCipher.java:137)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:137)
	at it.auties.whatsapp.socket.MessageHandler.decodeMessageBytes(MessageHandler.java:479)
	... 38 more
Okt. 22, 2022 9:15:08 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
FATAL: Ignored failure
```

**Comment by Auties00** [comment]
This issue is being tracked in https://github.com/Auties00/WhatsappWeb4j/issues/162
