### ISSUE TITLE
Error after scan the qrcode

### ISSUE THREAD

**Issue by NiotGG** [Auties00/WhatsappWeb4j#192]
I am receiving this error after scan the qrcode:

```
nov. 27, 2022 6:11:44 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Socket failure at ERRONEOUS_NODE
it.auties.whatsapp.exception.ErroneousNodeRequestException: Cannot process request Request[id=df-10, body=Node[description=iq, attributes={xmlns=w:profile:picture, to=s.whatsapp.net, id=df-10, type=get, target=556296411060@s.whatsapp.net}, content=[Node[description=picture, attributes={query=url}]]], future=java.util.concurrent.CompletableFuture@76d464d8[Not completed, 1 dependents], caller=java.lang.RuntimeException] with Node[description=iq, attributes={from=s.whatsapp.net, id=df-10, type=error}, content=[Node[description=error, attributes={code=404, text=item-not-found}]]]
        at it.auties.whatsapp.model.request.Request.complete(Request.java:149)
        at it.auties.whatsapp.controller.Store.deleteAndComplete(Store.java:657)
        at it.auties.whatsapp.controller.Store.lambda$resolvePendingRequest$10(Store.java:448)
        at java.base/java.util.Optional.map(Optional.java:260)
        at it.auties.whatsapp.controller.Store.resolvePendingRequest(Store.java:448)
        at it.auties.whatsapp.socket.SocketHandler.handleNode(SocketHandler.java:200)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at it.auties.whatsapp.socket.SocketHandler.onBinary(SocketHandler.java:195)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
        at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
        at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
        at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
        at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
        at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
        at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
        at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException
        at it.auties.whatsapp.model.request.Request.<init>(Request.java:40)
        at it.auties.whatsapp.model.request.Request.of(Request.java:48)
        at it.auties.whatsapp.model.request.Node.toRequest(Node.java:294)
        at it.auties.whatsapp.socket.SocketHandler.send(SocketHandler.java:274)
        at it.auties.whatsapp.socket.SocketHandler.sendQuery(SocketHandler.java:348)
        at it.auties.whatsapp.socket.SocketHandler.sendQuery(SocketHandler.java:333)
        at it.auties.whatsapp.socket.SocketHandler.queryPicture(SocketHandler.java:378)
        at it.auties.whatsapp.socket.StreamHandler.updateUserPicture(StreamHandler.java:495)
        at it.auties.whatsapp.socket.StreamHandler.sendStatusUpdate(StreamHandler.java:472)
        at it.auties.whatsapp.socket.StreamHandler.digestSuccess(StreamHandler.java:438)
        at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:74)
        at it.auties.whatsapp.socket.SocketHandler.handleNode(SocketHandler.java:201)
        ... 31 more
nov. 27, 2022 6:11:44 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Ignored failure
```

this is my code:

```
Whatsapp.Options options = Whatsapp.Options.newOptions()
                .id(Integer.valueOf(id))
                .autodetectListeners(true)
                .defaultSerialization(true)
                .textPreviewSetting(TextPreviewSetting.ENABLED_WITH_INFERENCE)
                .description("WhatsApp Web")
                .historyLength(HistoryLength.THREE_MONTHS)
                .errorHandler(ErrorHandler.toTerminal())
                .qrHandler(QrHandler.toTerminal()).build();


        whatsapp = Whatsapp.newConnection(options);

        whatsapp.connect().join().await();
```

**Comment by hewrie** [comment]
no solution yet? i have same error too..

**Comment by Auties00** [comment]
> no solution yet? i have same error too..

We solved it on telegram. What error are you seeing?

**Comment by hewrie** [comment]
this is my error. what channel on telegram, i'll join 

Dec 16, 2022 6:43:52 AM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Socket failure at ERRONEOUS_NODE
it.auties.whatsapp.exception.ErroneousNodeRequestException: Cannot process request Request[id=21-9, body=Node[description=iq, attributes={xmlns=w:profile:picture, to=s.whatsapp.net, id=21-9, type=get, target=xxxxxxxx@s.whatsapp.net}, content=[Node[description=picture, attributes={query=url}]]], future=java.util.concurrent.CompletableFuture@71536d2b[Not completed, 1 dependents], caller=java.lang.RuntimeException] with Node[description=iq, attributes={from=s.whatsapp.net, id=21-9, type=error}, content=[Node[description=error, attributes={code=404, text=item-not-found}]]]
	at it.auties.whatsapp.model.request.Request.complete(Request.java:149)
	at it.auties.whatsapp.controller.Store.deleteAndComplete(Store.java:657)
	at it.auties.whatsapp.controller.Store.lambda$resolvePendingRequest$10(Store.java:448)
	at java.base/java.util.Optional.map(Optional.java:260)
	at it.auties.whatsapp.controller.Store.resolvePendingRequest(Store.java:448)
	at it.auties.whatsapp.socket.SocketHandler.handleNode(SocketHandler.java:200)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.socket.SocketHandler.onBinary(SocketHandler.java:195)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
	at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException
	at it.auties.whatsapp.model.request.Request.<init>(Request.java:40)
	at it.auties.whatsapp.model.request.Request.of(Request.java:48)
	at it.auties.whatsapp.model.request.Node.toRequest(Node.java:294)
	at it.auties.whatsapp.socket.SocketHandler.send(SocketHandler.java:274)
	at it.auties.whatsapp.socket.SocketHandler.sendQuery(SocketHandler.java:348)
	at it.auties.whatsapp.socket.SocketHandler.sendQuery(SocketHandler.java:333)
	at it.auties.whatsapp.socket.SocketHandler.queryPicture(SocketHandler.java:378)
	at it.auties.whatsapp.socket.StreamHandler.updateUserPicture(StreamHandler.java:495)
	at it.auties.whatsapp.socket.StreamHandler.sendStatusUpdate(StreamHandler.java:472)
	at it.auties.whatsapp.socket.StreamHandler.digestSuccess(StreamHandler.java:438)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:74)
	at it.auties.whatsapp.socket.SocketHandler.handleNode(SocketHandler.java:201)
	... 31 more
Dec 16, 2022 6:43:52 AM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Ignored failure

**Comment by NeilDuToit92** [comment]
I had this same issue and was able to get around it by deleting all the files in the `$HOME/.whatsappweb4j` directory on my PC.

**Comment by Auties00** [comment]
> this is my error. what channel on telegram, i'll join
> 
> Dec 16, 2022 6:43:52 AM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1 SEVERE: Socket failure at ERRONEOUS_NODE it.auties.whatsapp.exception.ErroneousNodeRequestException: Cannot process request Request[id=21-9, body=Node[description=iq, attributes={xmlns=w:profile:picture, to=s.whatsapp.net, id=21-9, type=get, target=[xxxxxxxx@s.whatsapp.net](mailto:xxxxxxxx@s.whatsapp.net)}, content=[Node[description=picture, attributes={query=url}]]], future=java.util.concurrent.CompletableFuture@71536d2b[Not completed, 1 dependents], caller=java.lang.RuntimeException] with Node[description=iq, attributes={from=s.whatsapp.net, id=21-9, type=error}, content=[Node[description=error, attributes={code=404, text=item-not-found}]]] at it.auties.whatsapp.model.request.Request.complete(Request.java:149) at it.auties.whatsapp.controller.Store.deleteAndComplete(Store.java:657) at it.auties.whatsapp.controller.Store.lambda$resolvePendingRequest$10(Store.java:448) at java.base/java.util.Optional.map(Optional.java:260) at it.auties.whatsapp.controller.Store.resolvePendingRequest(Store.java:448) at it.auties.whatsapp.socket.SocketHandler.handleNode(SocketHandler.java:200) at java.base/java.lang.Iterable.forEach(Iterable.java:75) at it.auties.whatsapp.socket.SocketHandler.onBinary(SocketHandler.java:195) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556) at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655) at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591) at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806) at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183) at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70) at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819) at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726) at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452) at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91) at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68) at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248) at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88) at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246) at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178) at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118) at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96) at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51) at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510) at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82) at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83) at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101) at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) at java.base/java.lang.Thread.run(Thread.java:833) Caused by: java.lang.RuntimeException at it.auties.whatsapp.model.request.Request.(Request.java:40) at it.auties.whatsapp.model.request.Request.of(Request.java:48) at it.auties.whatsapp.model.request.Node.toRequest(Node.java:294) at it.auties.whatsapp.socket.SocketHandler.send(SocketHandler.java:274) at it.auties.whatsapp.socket.SocketHandler.sendQuery(SocketHandler.java:348) at it.auties.whatsapp.socket.SocketHandler.sendQuery(SocketHandler.java:333) at it.auties.whatsapp.socket.SocketHandler.queryPicture(SocketHandler.java:378) at it.auties.whatsapp.socket.StreamHandler.updateUserPicture(StreamHandler.java:495) at it.auties.whatsapp.socket.StreamHandler.sendStatusUpdate(StreamHandler.java:472) at it.auties.whatsapp.socket.StreamHandler.digestSuccess(StreamHandler.java:438) at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:74) at it.auties.whatsapp.socket.SocketHandler.handleNode(SocketHandler.java:201) ... 31 more Dec 16, 2022 6:43:52 AM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1 SEVERE: Ignored failure

Use the latest commit

**Comment by Auties00** [comment]
> I had this same issue and was able to get around it by deleting all the files in the `$HOME/.whatsappweb4j` directory on my PC.

This happened probably because you changed version in the meanwhile
