### ISSUE TITLE
HmacValidationException: decode_snapshot

### ISSUE THREAD

**Issue by hewrie** [Auties00/WhatsappWeb4j#197]
is there a newer version of 3.0-RC28? suddenly I had an error. an api can't send message. an error appears like this:
Dec 21, 2022 3:47:56 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Socket failure at PUSH_APP_STATE
java.util.concurrent.CompletionException: java.lang.RuntimeException: Cannot parse patch(1 tries)
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.RuntimeException: Cannot parse patch(1 tries)
        at it.auties.whatsapp.socket.AppStateHandler.decodeSync(AppStateHandler.java:249)
        at it.auties.whatsapp.socket.AppStateHandler.lambda$decodeSyncs$14(AppStateHandler.java:212)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at it.auties.whatsapp.socket.AppStateHandler.decodeSyncs(AppStateHandler.java:217)
        at it.auties.whatsapp.socket.AppStateHandler.lambda$pull$11(AppStateHandler.java:202)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        ... 6 more
Caused by: it.auties.whatsapp.exception.HmacValidationException: decode_snapshot
        at jdk.internal.reflect.GeneratedConstructorAccessor27.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at it.auties.whatsapp.util.Validate.createThrowable(Validate.java:29)
        at it.auties.whatsapp.util.Validate.isTrue(Validate.java:14)
        at it.auties.whatsapp.socket.AppStateHandler.decodeSnapshot(AppStateHandler.java:508)
        at it.auties.whatsapp.socket.AppStateHandler.decodeSync(AppStateHandler.java:225)
        ... 19 more
Dec 21, 2022 3:47:56 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Ignored failure

**Comment by Auties00** [comment]
> is there a newer version of 3.0-RC28? suddenly I had an error. an api can't send message. an error appears like this: Dec 21, 2022 3:47:56 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1 SEVERE: Socket failure at PUSH_APP_STATE java.util.concurrent.CompletionException: java.lang.RuntimeException: Cannot parse patch(1 tries) at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) Caused by: java.lang.RuntimeException: Cannot parse patch(1 tries) at it.auties.whatsapp.socket.AppStateHandler.decodeSync(AppStateHandler.java:249) at it.auties.whatsapp.socket.AppStateHandler.lambda$decodeSyncs$14(AppStateHandler.java:212) at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) at it.auties.whatsapp.socket.AppStateHandler.decodeSyncs(AppStateHandler.java:217) at it.auties.whatsapp.socket.AppStateHandler.lambda$pull$11(AppStateHandler.java:202) at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ... 6 more Caused by: it.auties.whatsapp.exception.HmacValidationException: decode_snapshot at jdk.internal.reflect.GeneratedConstructorAccessor27.newInstance(Unknown Source) at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) at it.auties.whatsapp.util.Validate.createThrowable(Validate.java:29) at it.auties.whatsapp.util.Validate.isTrue(Validate.java:14) at it.auties.whatsapp.socket.AppStateHandler.decodeSnapshot(AppStateHandler.java:508) at it.auties.whatsapp.socket.AppStateHandler.decodeSync(AppStateHandler.java:225) ... 19 more Dec 21, 2022 3:47:56 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1 SEVERE: Ignored failure

You can try to disconnect all your devices from Whatsapp, repair it with the library and see if it's fixed
