### ISSUE TITLE
Issues with version 3

### ISSUE THREAD

**Issue by ZiemlichUndead** [Auties00/WhatsappWeb4j#198]
I cant tell what exactly those issues are but version 3 of WhatsappWeb4J crashes almost every time for me.
Either I get this error and the session breaks:
`Dez. 26, 2022 7:21:30 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SCHWERWIEGEND: Socket failure at MESSAGE
java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because the return value of "it.auties.whatsapp.model.sync.HistorySync.pastParticipants()" is null
	at it.auties.whatsapp.socket.MessageHandler.handleHistorySync(MessageHandler.java:825)
	at it.auties.whatsapp.socket.MessageHandler.handleProtocolMessage(MessageHandler.java:737)
	at it.auties.whatsapp.socket.MessageHandler.saveMessage(MessageHandler.java:694)
	at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:488)
	at it.auties.whatsapp.socket.MessageHandler.lambda$decode$36(MessageHandler.java:394)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:394)
	at it.auties.whatsapp.socket.SocketHandler.decodeMessage(SocketHandler.java:327)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:81)
	at it.auties.whatsapp.socket.SocketHandler.handleNode(SocketHandler.java:210)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.socket.SocketHandler.onBinary(SocketHandler.java:204)
	at jdk.internal.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
	at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)
Dez. 26, 2022 7:21:30 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SCHWERWIEGEND: Ignored failure
Dez. 26, 2022 7:21:34 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SCHWERWIEGEND: Socket failure at INITIAL_APP_STATE_SYNC
java.util.concurrent.CompletionException: java.lang.RuntimeException: Cannot parse patch(3 tries)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.RuntimeException: Cannot parse patch(3 tries)
	at it.auties.whatsapp.socket.AppStateHandler.decodeSync(AppStateHandler.java:248)
	at it.auties.whatsapp.socket.AppStateHandler.decodeSync(AppStateHandler.java:251)
	at it.auties.whatsapp.socket.AppStateHandler.decodeSync(AppStateHandler.java:251)
	at it.auties.whatsapp.socket.AppStateHandler.lambda$decodeSyncs$15(AppStateHandler.java:211)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at it.auties.whatsapp.socket.AppStateHandler.decodeSyncs(AppStateHandler.java:216)
	at it.auties.whatsapp.socket.AppStateHandler.lambda$pull$13(AppStateHandler.java:202)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 7 more
Caused by: it.auties.protobuf.serializer.exception.ProtobufDeserializationException: Cannot deserialize field 2 inside it.auties.whatsapp.model.sync.ActionDataSync: cannot decode embedded message with type it.auties.whatsapp.model.sync.ActionValueSync
	at it.auties.protobuf.serializer.jackson.ProtobufParser.readEmbeddedMessage(ProtobufParser.java:321)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.readDelimited(ProtobufParser.java:284)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.readDelimitedWithConversion(ProtobufParser.java:241)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.readValueAndToken(ProtobufParser.java:211)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.nextToken(ProtobufParser.java:159)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:289)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1583)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1598)
	at it.auties.protobuf.serializer.jackson.ProtobufMapper.readMessage(ProtobufMapper.java:34)
	at it.auties.whatsapp.socket.AppStateHandler.decodeMutation(AppStateHandler.java:553)
	at it.auties.whatsapp.socket.AppStateHandler.lambda$decodeMutations$37(AppStateHandler.java:534)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at it.auties.whatsapp.socket.AppStateHandler.decodeMutations(AppStateHandler.java:535)
	at it.auties.whatsapp.socket.AppStateHandler.decodePatch(AppStateHandler.java:470)
	at it.auties.whatsapp.socket.AppStateHandler.lambda$decodePatches$32(AppStateHandler.java:447)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at it.auties.whatsapp.socket.AppStateHandler.decodePatches(AppStateHandler.java:451)
	at it.auties.whatsapp.socket.AppStateHandler.decodeSync(AppStateHandler.java:233)
	... 22 more
Caused by: it.auties.protobuf.serializer.exception.ProtobufDeserializationException: Cannot deserialize field timeFormatAction(30) in it.auties.whatsapp.model.sync.ActionValueSync: no converter found from it.auties.whatsapp.model.action.TimeFormatAction to it.auties.whatsapp.model.action.TimeFormatAction
	at it.auties.protobuf.serializer.jackson.ProtobufParser.lambda$findConverter$1(ProtobufParser.java:263)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.findConverter(ProtobufParser.java:262)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.readDelimitedWithConversion(ProtobufParser.java:248)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.readValueAndToken(ProtobufParser.java:211)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.nextToken(ProtobufParser.java:159)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:289)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4706)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2879)
	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:2304)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.readEmbeddedMessage(ProtobufParser.java:318)
	... 56 more
Dez. 26, 2022 7:21:34 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SCHWERWIEGEND: Restoring session
`

or this error:

`Dez. 26, 2022 7:22:52 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SCHWERWIEGEND: Socket failure at INITIAL_APP_STATE_SYNC
java.util.concurrent.CompletionException: java.lang.RuntimeException: Cannot parse patch(3 tries)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.RuntimeException: Cannot parse patch(3 tries)
	at it.auties.whatsapp.socket.AppStateHandler.decodeSync(AppStateHandler.java:248)
	at it.auties.whatsapp.socket.AppStateHandler.decodeSync(AppStateHandler.java:251)
	at it.auties.whatsapp.socket.AppStateHandler.decodeSync(AppStateHandler.java:251)
	at it.auties.whatsapp.socket.AppStateHandler.lambda$decodeSyncs$15(AppStateHandler.java:211)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at it.auties.whatsapp.socket.AppStateHandler.decodeSyncs(AppStateHandler.java:216)
	at it.auties.whatsapp.socket.AppStateHandler.lambda$pull$13(AppStateHandler.java:202)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 7 more
Caused by: it.auties.protobuf.serializer.exception.ProtobufDeserializationException: Cannot deserialize field 2 inside it.auties.whatsapp.model.sync.ActionDataSync: cannot decode embedded message with type it.auties.whatsapp.model.sync.ActionValueSync
	at it.auties.protobuf.serializer.jackson.ProtobufParser.readEmbeddedMessage(ProtobufParser.java:321)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.readDelimited(ProtobufParser.java:284)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.readDelimitedWithConversion(ProtobufParser.java:241)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.readValueAndToken(ProtobufParser.java:211)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.nextToken(ProtobufParser.java:159)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:289)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1583)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1598)
	at it.auties.protobuf.serializer.jackson.ProtobufMapper.readMessage(ProtobufMapper.java:34)
	at it.auties.whatsapp.socket.AppStateHandler.decodeMutation(AppStateHandler.java:553)
	at it.auties.whatsapp.socket.AppStateHandler.lambda$decodeMutations$37(AppStateHandler.java:534)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at it.auties.whatsapp.socket.AppStateHandler.decodeMutations(AppStateHandler.java:535)
	at it.auties.whatsapp.socket.AppStateHandler.decodeSnapshot(AppStateHandler.java:505)
	at it.auties.whatsapp.socket.AppStateHandler.decodeSync(AppStateHandler.java:224)
	... 22 more
Caused by: it.auties.protobuf.serializer.exception.ProtobufDeserializationException: Cannot deserialize field primaryVersionAction(32) in it.auties.whatsapp.model.sync.ActionValueSync: no converter found from it.auties.whatsapp.model.action.PrimaryVersionAction to it.auties.whatsapp.model.action.PrimaryVersionAction
	at it.auties.protobuf.serializer.jackson.ProtobufParser.lambda$findConverter$1(ProtobufParser.java:263)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.findConverter(ProtobufParser.java:262)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.readDelimitedWithConversion(ProtobufParser.java:248)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.readValueAndToken(ProtobufParser.java:211)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.nextToken(ProtobufParser.java:159)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:289)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4706)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2879)
	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:2304)
	at it.auties.protobuf.serializer.jackson.ProtobufParser.readEmbeddedMessage(ProtobufParser.java:318)
	... 45 more
Dez. 26, 2022 7:22:52 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SCHWERWIEGEND: Restoring session
`

**Comment by ZiemlichUndead** [comment]
I also wanna note that I also did have a lot of issues with RC28. Not exactly the same issues with sessions breaking immediately but I could not get a stable session on RC28 for more that 6 hours.

**Comment by Auties00** [comment]
I should have though about that field possibly being null, I'm currently on vacation but I'll try to push a commit from my phone

**Comment by Auties00** [comment]
Okay I pushed it to the master Branch, you can use that to see if it's fixed

**Comment by Auties00** [comment]
> I also wanna note that I also did have a lot of issues with RC28. Not exactly the same issues with sessions breaking immediately but I could not get a stable session on RC28 for more that 6 hours.

Yeah sorry about that, i was working out some things for a stable release which lead me to break quite a lot of things

**Comment by ZiemlichUndead** [comment]
> Okay I pushed it to the master Branch, you can use that to see if it's fixed

It seems like I cannot build master branch because a class is missing in your protobuf library.
`java: cannot find symbol
  symbol:   class ProtobufName
  location: package it.auties.protobuf.base`

**Comment by ZiemlichUndead** [comment]
> I should have though about that field possibly being null, I'm currently on vacation but I'll try to push a commit from my phone

But hey no worries, enjoy your vacation. Im running fine on RC26 for a while now so I definitely don't mind you taking your time to fix issues on newer versions.

**Comment by NeilDuToit92** [comment]
> > Okay I pushed it to the master Branch, you can use that to see if it's fixed
> 
> It seems like I cannot build master branch because a class is missing in your protobuf library. `java: cannot find symbol symbol: class ProtobufName location: package it.auties.protobuf.base`

Check out and `mvn install` the ModernProtobuf library first, that should get you going: https://github.com/Auties00/ModernProtobuf

**Comment by ZiemlichUndead** [comment]
Using the latest commit on master everything seems to run fine now. Will report back if i find any issues.

**Comment by Auties00** [comment]
> Using the latest commit on master everything seems to run fine now. Will report back if i find any issues.

Good, btw I released 3.0.1
