### ISSUE TITLE
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Boolean

### ISSUE THREAD

**Issue by GedMarc** [Auties00/WhatsappWeb4j#20]
```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Boolean (java.lang.Integer and java.lang.Boolean are in module java.base of loader 'bootstrap')
	at it.auties.whatsapp4j.model.WhatsappGenericMessage.invokeCheckerMethod(WhatsappGenericMessage.java:64)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
```

```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Boolean (java.lang.Integer and java.lang.Boolean are in module java.base of loader 'bootstrap')
	at it.auties.whatsapp4j.model.WhatsappGenericMessage.invokeCheckerMethod(WhatsappGenericMessage.java:64)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
	at it.auties.whatsapp4j.model.WhatsappGenericMessage.contextInfo(WhatsappGenericMessage.java:41)
	at it.auties.whatsapp4j.model.WhatsappUserMessage.<init>(WhatsappUserMessage.java:54)
	at it.auties.whatsapp4j.model.WhatsappGenericMessage.<init>(WhatsappGenericMessage.java:29)
	at it.auties.whatsapp4j.utils.WhatsappMessageFactory.buildUserMessageFromProtobuf(WhatsappMessageFactory.java:42)
	at it.auties.whatsapp4j.utils.WhatsappMessageFactory.buildMessageFromProtobuf(WhatsappMessageFactory.java:20)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at it.auties.whatsapp4j.manager.WhatsappDataManager.processMessagesFromNodes(WhatsappDataManager.java:481)
	at it.auties.whatsapp4j.manager.WhatsappDataManager.processMessages(WhatsappDataManager.java:422)
	at it.auties.whatsapp4j.manager.WhatsappDataManager.parseAction(WhatsappDataManager.java:265)
	at it.auties.whatsapp4j.manager.WhatsappDataManager.digestWhatsappNode(WhatsappDataManager.java:244)
	at it.auties.whatsapp4j.socket.WhatsappWebSocket.onBinaryMessage(WhatsappWebSocket.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at io.undertow.websockets.jsr.annotated.BoundMethod.invoke(BoundMethod.java:87)
	at io.undertow.websockets.jsr.annotated.AnnotatedEndpoint$2.onMessage(AnnotatedEndpoint.java:142)
	at io.undertow.websockets.jsr.FrameHandler$6.run(FrameHandler.java:243)
	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:170)
	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:167)
	at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:610)
	at io.undertow.websockets.jsr.ServerWebSocketContainer$6.run(ServerWebSocketContainer.java:596)
	at io.undertow.websockets.jsr.OrderedExecutor$ExecutorTask.run(OrderedExecutor.java:67)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
	at java.base/java.lang.Thread.run(Thread.java:831)

```

![image](https://user-images.githubusercontent.com/5367513/116868479-20d13300-ac0f-11eb-801f-1cc8a3b26f1b.png)

**Comment by GedMarc** [comment]
I went this route : 

WhatsappGenericMessage
```
/**
     * Returns the ContextInfo of this message if available
     *
     * @return a non empty optional if this message has a context
     */
    @Override
    @SneakyThrows
    public @NotNull Optional<WhatsappProtobuf.ContextInfo> contextInfo() {
        var methods = findCheckerMethods();
        var propertyChecker = methods.stream()
                                     .filter(a -> a.getName()
                                                   .startsWith("get") || a.getName()
                                                                          .startsWith("is"))
                                     .filter(this::invokeCheckerMethod)
                                     .findAny();
        if(propertyChecker.isEmpty()){
            return Optional.empty();
        }

        var propertyGetter = findGetterMethod(propertyChecker.get());
        var property = propertyGetter.invoke(info.getMessage());

        return findContextInfoMethod(property).map(method -> invokeContextInfoGetter(property, method));
    }
```

**Comment by Auties00** [comment]
> ```
> java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Boolean (java.lang.Integer and java.lang.Boolean are in module java.base of loader 'bootstrap')
> 	at it.auties.whatsapp4j.model.WhatsappGenericMessage.invokeCheckerMethod(WhatsappGenericMessage.java:64)
> 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
> ```
> 
> ```
> java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Boolean (java.lang.Integer and java.lang.Boolean are in module java.base of loader 'bootstrap')
> 	at it.auties.whatsapp4j.model.WhatsappGenericMessage.invokeCheckerMethod(WhatsappGenericMessage.java:64)
> 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
> 	at java.base/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706)
> 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
> 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
> 	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
> 	at it.auties.whatsapp4j.model.WhatsappGenericMessage.contextInfo(WhatsappGenericMessage.java:41)
> 	at it.auties.whatsapp4j.model.WhatsappUserMessage.<init>(WhatsappUserMessage.java:54)
> 	at it.auties.whatsapp4j.model.WhatsappGenericMessage.<init>(WhatsappGenericMessage.java:29)
> 	at it.auties.whatsapp4j.utils.WhatsappMessageFactory.buildUserMessageFromProtobuf(WhatsappMessageFactory.java:42)
> 	at it.auties.whatsapp4j.utils.WhatsappMessageFactory.buildMessageFromProtobuf(WhatsappMessageFactory.java:20)
> 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
> 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
> 	at it.auties.whatsapp4j.manager.WhatsappDataManager.processMessagesFromNodes(WhatsappDataManager.java:481)
> 	at it.auties.whatsapp4j.manager.WhatsappDataManager.processMessages(WhatsappDataManager.java:422)
> 	at it.auties.whatsapp4j.manager.WhatsappDataManager.parseAction(WhatsappDataManager.java:265)
> 	at it.auties.whatsapp4j.manager.WhatsappDataManager.digestWhatsappNode(WhatsappDataManager.java:244)
> 	at it.auties.whatsapp4j.socket.WhatsappWebSocket.onBinaryMessage(WhatsappWebSocket.java:179)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
> 	at io.undertow.websockets.jsr.annotated.BoundMethod.invoke(BoundMethod.java:87)
> 	at io.undertow.websockets.jsr.annotated.AnnotatedEndpoint$2.onMessage(AnnotatedEndpoint.java:142)
> 	at io.undertow.websockets.jsr.FrameHandler$6.run(FrameHandler.java:243)
> 	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:170)
> 	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:167)
> 	at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:610)
> 	at io.undertow.websockets.jsr.ServerWebSocketContainer$6.run(ServerWebSocketContainer.java:596)
> 	at io.undertow.websockets.jsr.OrderedExecutor$ExecutorTask.run(OrderedExecutor.java:67)
> 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
> 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
> 	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
> 	at java.base/java.lang.Thread.run(Thread.java:831)
> ```
> 
> ![image](https://user-images.githubusercontent.com/5367513/116868479-20d13300-ac0f-11eb-801f-1cc8a3b26f1b.png)

Hello, 
are you using version 1.2 or 2.0-SNAPSHOT?

**Comment by Auties00** [comment]
Fixed in the latest commit

**Comment by GedMarc** [comment]
Thanks man! 

Sorry jumping between so many I am literally losing days xD
