### ISSUE TITLE
SEVERE: Socket failure at CRYPTOGRAPHY

### ISSUE THREAD

**Issue by DiegoAguilarZ** [Auties00/WhatsappWeb4j#202]
**Help, when i try to login with qr code i get this error. im using the 3.0.2 version.**

```
ene. 13, 2023 11:00:08 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Socket failure at CRYPTOGRAPHY
it.auties.whatsapp.exception.UnknownStreamException: Detected a bad mac
	at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:462)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:108)
	at it.auties.whatsapp.socket.SocketHandler.handleNode(SocketHandler.java:227)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.socket.SocketHandler.onBinary(SocketHandler.java:221)
	at jdk.internal.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
	at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)
ene. 13, 2023 11:00:08 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Restoring session
```

**Comment by Auties00** [comment]
> **Help, when i try to login with qr code i get this error. im using the 3.0.2 version.**
> 
> ```
> ene. 13, 2023 11:00:08 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
> SEVERE: Socket failure at CRYPTOGRAPHY
> it.auties.whatsapp.exception.UnknownStreamException: Detected a bad mac
> 	at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:462)
> 	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:108)
> 	at it.auties.whatsapp.socket.SocketHandler.handleNode(SocketHandler.java:227)
> 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
> 	at it.auties.whatsapp.socket.SocketHandler.onBinary(SocketHandler.java:221)
> 	at jdk.internal.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
> 	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
> 	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
> 	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
> 	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
> 	at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
> 	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
> 	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
> 	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
> 	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
> 	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
> 	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
> 	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
> 	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
> 	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
> 	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
> 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
> 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
> 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
> 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> ene. 13, 2023 11:00:08 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
> SEVERE: Restoring session
> ```

Can you try to delete all of your sessions from the WhatsApp app and try again ?

**Comment by DiegoAguilarZ** [comment]
i tried it and didnt work.

**Comment by shmezi** [comment]
Randomly just started having this issue. Will be happy to send whatever is needed to help debug.

**Comment by Auties00** [comment]
I might have created this accidentally, does this happen also on the master branch or only or 3.0.2?

**Comment by shmezi** [comment]
No clue, how would I get the main branch ?

**Comment by Auties00** [comment]
> No clue, how would I get the main branch ?
Tracking in https://github.com/Auties00/WhatsappWeb4j/issues/203
