### ISSUE TITLE
api.createGroup fails on duplicate group name

### ISSUE THREAD

**Issue by GedMarc** [Auties00/WhatsappWeb4j#21]
```
CompletableFuture<WhatsappChat> groupCreateFuture = api.createGroup("Duplicate Group Name", whatsappContacts).get();
```

Looking good so far!

```
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot convert WhatsappNode[description=response, attrs={duplicate=true, type=chat}, content=null] to it.auties.whatsapp4j.response.impl.ChatResponse as an exception occurred while initializing said class
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069)
	at it.auties.whatsapp4j.YourAwesomeListener.onContactsReceived(YourAwesomeListener.java:57)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.IllegalArgumentException: Cannot convert WhatsappNode[description=response, attrs={duplicate=true, type=chat}, content=null] to it.auties.whatsapp4j.response.impl.ChatResponse as an exception occurred while initializing said class
	at it.auties.whatsapp4j.response.model.BinaryResponse.toModel(BinaryResponse.java:31)
	at it.auties.whatsapp4j.request.model.Request.lambda$complete$0(Request.java:105)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1764)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at it.auties.whatsapp4j.response.model.BinaryResponse.toModel(BinaryResponse.java:29)
	... 10 more
Caused by: java.lang.IllegalArgumentException: WhatsappAPI: Cannot parse WhatsappNode[description=response, attrs={duplicate=true, type=chat}, content=null] as WhatsappChat
	at it.auties.whatsapp4j.response.impl.ChatResponse.lambda$new$1(ChatResponse.java:27)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at it.auties.whatsapp4j.response.impl.ChatResponse.<init>(ChatResponse.java:27)
	... 16 more
```

**Comment by Auties00** [comment]
> ```
> CompletableFuture<WhatsappChat> groupCreateFuture = api.createGroup("Duplicate Group Name", whatsappContacts).get();
> ```
> 
> Looking good so far!
> 
> ```
> java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot convert WhatsappNode[description=response, attrs={duplicate=true, type=chat}, content=null] to it.auties.whatsapp4j.response.impl.ChatResponse as an exception occurred while initializing said class
> 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
> 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069)
> 	at it.auties.whatsapp4j.YourAwesomeListener.onContactsReceived(YourAwesomeListener.java:57)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> 	at java.base/java.lang.Thread.run(Thread.java:831)
> Caused by: java.lang.IllegalArgumentException: Cannot convert WhatsappNode[description=response, attrs={duplicate=true, type=chat}, content=null] to it.auties.whatsapp4j.response.impl.ChatResponse as an exception occurred while initializing said class
> 	at it.auties.whatsapp4j.response.model.BinaryResponse.toModel(BinaryResponse.java:31)
> 	at it.auties.whatsapp4j.request.model.Request.lambda$complete$0(Request.java:105)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1764)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:295)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
> 	at it.auties.whatsapp4j.response.model.BinaryResponse.toModel(BinaryResponse.java:29)
> 	... 10 more
> Caused by: java.lang.IllegalArgumentException: WhatsappAPI: Cannot parse WhatsappNode[description=response, attrs={duplicate=true, type=chat}, content=null] as WhatsappChat
> 	at it.auties.whatsapp4j.response.impl.ChatResponse.lambda$new$1(ChatResponse.java:27)
> 	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
> 	at it.auties.whatsapp4j.response.impl.ChatResponse.<init>(ChatResponse.java:27)
> 	... 16 more
> ```

I haven't managed to reproduce this bug, can you post the entire code?

**Comment by GedMarc** [comment]
will update my test cases :) 
https://github.com/GedMarc/GuicedEE-Services/blob/master/whatsapp-web-4j/src/test/java/it/auties/whatsapp4j/wa4jtest.java

essentially though creating a group twice with the same contacts causes this exception (group name seems only to be applicable  on first create)

**Comment by GedMarc** [comment]
Running that test twice causes this error on this line :)

https://github.com/GedMarc/GuicedEE-Services/blob/9e553879e935b0eeac23bc4d12767ec143df2eb7/whatsapp-web-4j/src/test/java/it/auties/whatsapp4j/YourAwesomeListener.java#L69

**Comment by Auties00** [comment]
> Running that test twice causes this error on this line :)
> 
> https://github.com/GedMarc/GuicedEE-Services/blob/9e553879e935b0eeac23bc4d12767ec143df2eb7/whatsapp-web-4j/src/test/java/it/auties/whatsapp4j/YourAwesomeListener.java#L69

I'm actually very confused, this doesn't happen on my system:
```
INFO: Created group: WhatsappChat(name=Chat 1, jid=whatever@g.us, messages=[], presences={}, newJid=Optional.empty, timestamp=1620322987, mute=WhatsappMute[time=0], unreadMessages=0, pinned=Optional.empty, ephemeralMessageDuration=Optional.empty, ephemeralMessagesToggleTime=Optional.empty, isArchived=false, isReadOnly=false, isSpam=false)
mag 06, 2021 7:43:08 PM it.auties.whatsapp4j.test.WhatsappTest lambda$testGroupCreation$3
INFO: Created group: WhatsappChat(name=Chat 1, whatever@g.us, messages=[WhatsappServerMessage()], presences={}, newJid=Optional.empty, timestamp=1620322987, mute=WhatsappMute[time=0], unreadMessages=0, pinned=Optional.empty, ephemeralMessageDuration=Optional.empty, ephemeralMessagesToggleTime=Optional.empty, isArchived=false, isReadOnly=false, isSpam=false)
```

**Comment by Auties00** [comment]
> > Running that test twice causes this error on this line :)
> > https://github.com/GedMarc/GuicedEE-Services/blob/9e553879e935b0eeac23bc4d12767ec143df2eb7/whatsapp-web-4j/src/test/java/it/auties/whatsapp4j/YourAwesomeListener.java#L69
> 
> I'm actually very confused, this doesn't happen on my system:
> 
> ```
> INFO: Created group: WhatsappChat(name=Chat 1, jid=whatever@g.us, messages=[], presences={}, newJid=Optional.empty, timestamp=1620322987, mute=WhatsappMute[time=0], unreadMessages=0, pinned=Optional.empty, ephemeralMessageDuration=Optional.empty, ephemeralMessagesToggleTime=Optional.empty, isArchived=false, isReadOnly=false, isSpam=false}
> INFO: Created group: WhatsappChat(name=Chat 1, whatever@g.us, messages=[WhatsappServerMessage()], presences={}, newJid=Optional.empty, timestamp=1620322987, mute=WhatsappMute[time=0], unreadMessages=0, pinned=Optional.empty, ephemeralMessageDuration=Optional.empty, ephemeralMessagesToggleTime=Optional.empty, isArchived=false, isReadOnly=false, isSpam=false)
> ```

wait maybe I get it

**Comment by Auties00** [comment]
> Running that test twice causes this error on this line :)
> 
> https://github.com/GedMarc/GuicedEE-Services/blob/9e553879e935b0eeac23bc4d12767ec143df2eb7/whatsapp-web-4j/src/test/java/it/auties/whatsapp4j/YourAwesomeListener.java#L69

never mind, it works. Can you please try to use the latest unreleased version?
