### ISSUE TITLE
Getting error Unhandled exception in endpoint it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket

### ISSUE THREAD

**Issue by DevOFVictory** [Auties00/WhatsappWeb4j#33]
Getting following error after connecting via. QR Code:
```
INFO: Unhandled exception in endpoint it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.
java.lang.NumberFormatException: null
	at java.base/java.lang.Integer.parseInt(Integer.java:622)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at it.auties.whatsapp4j.protobuf.chat.Chat.fromAttributes(Chat.java:143)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at it.auties.whatsapp4j.manager.WhatsappDataManager.parseChats(WhatsappDataManager.java:462)
	at it.auties.whatsapp4j.manager.WhatsappDataManager.parseResponse(WhatsappDataManager.java:393)
	at it.auties.whatsapp4j.manager.WhatsappDataManager.digestWhatsappNode(WhatsappDataManager.java:224)
	at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.onBinary(WhatsappWebSocket.java:208)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.access$100(AnnotatedEndpoint.java:66)
	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652)
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:559)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:800)
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
	at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:248)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:181)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:121)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:99)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
```

**Comment by Auties00** [comment]
This looks weird, mutes are supposed to not be nullable. Is this the only exception being thrown? Does the api work correctly even though this exception is thrown?

**Comment by DevOFVictory** [comment]
This is the only thrown exception, but the functions on the api object doesnt return anything. For example
```java
api.manager().chats();
```
returns an emty list.

**Comment by Auties00** [comment]
> This is the only thrown exception, but the functions on the api object doesnt return anything. For example
> 
> ```java
> api.manager().chats();
> ```
> 
> returns an emty list.

is this snippet in a WhatsappListener that implemements the method onChats()?

**Comment by DevOFVictory** [comment]
> is this snippet in a WhatsappListener that implements the method onChats()?
>>
My first code that didnt work looked like this:
```java
    public static void main(String[] args) {
        api = new WhatsappAPI();
        api.connect();

        System.out.println("Logged in");

        System.out.println(api.manager().chats());
    }
```
but even when I'm calling the method from a WhatsappListener, it doesn't work.

**Comment by Auties00** [comment]
> > is this snippet in a WhatsappListener that implements the method onChats()?
> > >
> 
> My first code that didnt work looked like this:
> 
> ```java
>     public static void main(String[] args) {
>         api = new WhatsappAPI();
>         api.connect();
> 
>         System.out.println("Logged in");
> 
>         System.out.println(api.manager().chats());
>     }
> ```
> 
> but even when I'm calling the method from a WhatsappListener, it doesn't work.

was it in the onChats method?

**Comment by DevOFVictory** [comment]
No, its the main method of the application.

**Comment by Auties00** [comment]
> No, its the main method of the application.

As stated [in the documentation](https://github.com/Auties00/WhatsappWeb4j#in-memory-data):

> **_IMPORTANT:_** When your program first starts up, these fields will be empty. To be notified when they are populated, implement the corresponding method in a WhatsappListener

Please try a snippet like this:
`
    public static void main(String[] args) {
        var api = new WhatsappAPI();
        api.registerListener(new MyListener(api));
        api.connect();
    }
    
    class MyListener implements WhatsappListener{
         private final WhatsappAPI api;
         public MyListener(WhatsappAPI api){
             this.api = api;
         }
         
         public void onLoggedIn(@NonNull UserInformationResponse info) {
              System.out.println("Connected :)");
         }

         public void onChats(){
             System.out.printf("Recived chats: %s%n", api.manager().chats());
         }
    }
`

**Comment by DevOFVictory** [comment]
Didn't work. Do I have to use the [latest commit](https://github.com/Auties00/WhatsappWeb4j/commit/240f667ff66935f6d27f3ecc6862044a5652a291) and if yes, how to set it as dependency in IntelliJ without maven release?

**Comment by Auties00** [comment]
> Didn't work. Do I have to use the [latest commit](https://github.com/Auties00/WhatsappWeb4j/commit/240f667ff66935f6d27f3ecc6862044a5652a291) and if yes, how to set it as dependency in IntelliJ without maven release?

It doesn't work because it still throws the same exception or because `api.manager().chats()` is empty?

**Comment by DevOFVictory** [comment]
The ```onChats()``` method doesnt execute AND the exception is being thrown.

**Comment by Auties00** [comment]
> The `onChats()` method doesnt execute AND the exception is being thrown.

Okay, I'll create a new release so you can test the fix

**Comment by Auties00** [comment]
> The `onChats()` method doesnt execute AND the exception is being thrown.

I've released version 2.1.2, check it out and tell me if the issue is fixed

**Comment by DevOFVictory** [comment]
Could you maybe create a maven release? It would simpify many things for me. :)

**Comment by Auties00** [comment]
> Could you maybe create a maven release? It would simpify many things for me. :)

It is indeed a maven release, maybe maven central took a couple of minutes to sync up, but it is available as of now:
https://repo1.maven.org/maven2/com/github/auties00/whatsappweb4j/2.1.2/

**Comment by DevOFVictory** [comment]
Thank you. This issue is fixed by the latest release! 😊
