### ISSUE TITLE
An error is being thrown when changing read status of a message

### ISSUE THREAD

**Issue by DevOFVictory** [Auties00/WhatsappWeb4j#36]
If you manually read a message with the connected mobile phone or if you use the method `api.markAsRead(chat);` the following error is being thrown, but it has no impact to the run time of the project.

Error:
```
INFO: Unhandled exception in endpoint it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.
java.lang.NullPointerException: Cannot invoke "it.auties.whatsapp4j.protobuf.info.MessageInfo$MessageInfoStatus.index()" because the return value of "it.auties.whatsapp4j.protobuf.info.MessageInfo.globalStatus()" is null
	at it.auties.whatsapp4j.manager.WhatsappDataManager.parseReceivedStatus(WhatsappDataManager.java:429)
	at it.auties.whatsapp4j.manager.WhatsappDataManager.parseAction(WhatsappDataManager.java:241)
	at it.auties.whatsapp4j.manager.WhatsappDataManager.digestWhatsappNode(WhatsappDataManager.java:221)
	at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.onBinary(WhatsappWebSocket.java:212)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.access$100(AnnotatedEndpoint.java:66)
	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652)
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:559)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:800)
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
	at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:248)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:181)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:121)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:99)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Auties00** [comment]
> If you manually read a message with the connected mobile phone or if you use the method `api.markAsRead(chat);` the following error is being thrown, but it has no impact to the run time of the project.
> 
> Error:
> 
> ```
> INFO: Unhandled exception in endpoint it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.
> java.lang.NullPointerException: Cannot invoke "it.auties.whatsapp4j.protobuf.info.MessageInfo$MessageInfoStatus.index()" because the return value of "it.auties.whatsapp4j.protobuf.info.MessageInfo.globalStatus()" is null
> 	at it.auties.whatsapp4j.manager.WhatsappDataManager.parseReceivedStatus(WhatsappDataManager.java:429)
> 	at it.auties.whatsapp4j.manager.WhatsappDataManager.parseAction(WhatsappDataManager.java:241)
> 	at it.auties.whatsapp4j.manager.WhatsappDataManager.digestWhatsappNode(WhatsappDataManager.java:221)
> 	at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.onBinary(WhatsappWebSocket.java:212)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
> 	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553)
> 	at org.glassfish.tyrus.core.AnnotatedEndpoint.access$100(AnnotatedEndpoint.java:66)
> 	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652)
> 	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:559)
> 	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:800)
> 	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
> 	at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
> 	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
> 	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725)
> 	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
> 	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
> 	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
> 	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
> 	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:248)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:181)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:121)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:99)
> 	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
> 	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
> 	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
> 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
> 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
> 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
> 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
> 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
> 	at java.base/java.lang.Thread.run(Thread.java:831)
> ```

Does this happen only with groups or also in one to one chats?

**Comment by DevOFVictory** [comment]
In all kinds of chats.

**Comment by Auties00** [comment]
> In all kinds of chats.

The issue should be fixed, I reopened the issue just to be sure that the fix works. I'll create a release as soon as possible

**Comment by Auties00** [comment]
> In all kinds of chats.

Version 2.1.4 is live
