### ISSUE TITLE
Changing the group icon picture seems not to work

### ISSUE THREAD

**Issue by DevOFVictory** [Auties00/WhatsappWeb4j#38]
I use this code to change the group icon, but it throws an `IllegalArgumentException` in `BinaryEncoder.java:167`:
```java
File myIcon = new File("group-icon.png");
byte[] fileBytes = Files.readAllBytes(myIcon.toPath());
WhatsappWebBot.getApi().changeGroupPicture(chat, fileBytes);
```

Full error:
```
java.lang.IllegalArgumentException: Cannot encode content [B@1862af00
	at it.auties.whatsapp4j.binary.BinaryEncoder.writeContent(BinaryEncoder.java:167)
	at it.auties.whatsapp4j.binary.BinaryEncoder.writeNode(BinaryEncoder.java:44)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp4j.binary.BinaryEncoder.writeContent(BinaryEncoder.java:156)
	at it.auties.whatsapp4j.binary.BinaryEncoder.writeNode(BinaryEncoder.java:44)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp4j.binary.BinaryEncoder.writeContent(BinaryEncoder.java:156)
	at it.auties.whatsapp4j.binary.BinaryEncoder.writeNode(BinaryEncoder.java:44)
	at it.auties.whatsapp4j.binary.BinaryEncoder.encodeMessage(BinaryEncoder.java:37)
	at it.auties.whatsapp4j.request.model.BinaryRequest.encode(BinaryRequest.java:113)
	at it.auties.whatsapp4j.request.model.BinaryRequest.send(BinaryRequest.java:92)
	at it.auties.whatsapp4j.whatsapp.WhatsappAPI.changeGroupPicture(WhatsappAPI.java:627)
```

**Comment by Auties00** [comment]
> ```java
> changeGroupPicture
> ```

As stated in the documentation, this feature is still in Beta and is not expected to work. I'm currently working on supporting the new multi-device beta, though, If this method is important for your project I could take a look

**Comment by DevOFVictory** [comment]
No, its not as important. I just noticed that this doesn't work yet. Take your time :)

**Comment by Auties00** [comment]
Implemented in md
