### ISSUE TITLE
Hmac validation failed

### ISSUE THREAD

**Issue by marthin88** [Auties00/WhatsappWeb4j#41]
Hi is everyone ever facing same problem like i did. this happen when i am receiving image or video form another user, but is fine when receiving text message. and is fine too when sending someone media message or text message.

Exception log :

> Exception in thread "pool-1-thread-1" java.lang.SecurityException: Cannot login: Hmac validation failed!
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at it.auties.whatsapp4j.utils.internal.Validate.isTrue(Validate.java:49)
	at it.auties.whatsapp4j.utils.internal.CypherUtils.mediaDecrypt(CypherUtils.java:180)
	at it.auties.whatsapp4j.utils.internal.CypherUtils.lambda$0(CypherUtils.java:156)
	at java.base/java.util.Optional.map(Optional.java:260)
	at it.auties.whatsapp4j.utils.internal.CypherUtils.mediaDecrypt(CypherUtils.java:156)
	at it.auties.whatsapp4j.protobuf.message.model.MediaMessage.decodedMedia(MediaMessage.java:33)
	at com.org.websmith.listener.WAlistener.onNewMessage(WAlistener.java:56)
	at it.auties.whatsapp4j.manager.WhatsappDataManager.lambda$51(WhatsappDataManager.java:589)
	at it.auties.whatsapp4j.manager.WhatsappDataManager.lambda$10(WhatsappDataManager.java:251)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

is any setting or configuration that must be check for decoding media message?
this app running using :

WhatsappWeb4j : v2.2.1
JDK : Java 16
OS: Windows 10

**Comment by Auties00** [comment]
> Hi is everyone ever facing same problem like i did. this happen when i am receiving image or video form another user, but is fine when receiving text message. and is fine too when sending someone media message or text message.
> 
> Exception log :
> 
> > Exception in thread "pool-1-thread-1" java.lang.SecurityException: Cannot login: Hmac validation failed!
> > at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> > at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
> > at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> > at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
> > at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
> > at it.auties.whatsapp4j.utils.internal.Validate.isTrue(Validate.java:49)
> > at it.auties.whatsapp4j.utils.internal.CypherUtils.mediaDecrypt(CypherUtils.java:180)
> > at it.auties.whatsapp4j.utils.internal.CypherUtils.lambda$0(CypherUtils.java:156)
> > at java.base/java.util.Optional.map(Optional.java:260)
> > at it.auties.whatsapp4j.utils.internal.CypherUtils.mediaDecrypt(CypherUtils.java:156)
> > at it.auties.whatsapp4j.protobuf.message.model.MediaMessage.decodedMedia(MediaMessage.java:33)
> > at com.org.websmith.listener.WAlistener.onNewMessage(WAlistener.java:56)
> > at it.auties.whatsapp4j.manager.WhatsappDataManager.lambda$51(WhatsappDataManager.java:589)
> > at it.auties.whatsapp4j.manager.WhatsappDataManager.lambda$10(WhatsappDataManager.java:251)
> > at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
> > at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> > at java.base/java.lang.Thread.run(Thread.java:831)
> 
> is any setting or configuration that must be check for decoding media message?
> this app running using :
> 
> WhatsappWeb4j : v2.2.1
> JDK : Java 16
> OS: Windows 10

Hello, I'm currently on vacation so I cannot fix this issue. This is happening because the protobuf of the message that you received has the fields of type byte [] corrupted as ModernProtoc, my custom implementation of protobuf, doesn't deserialize them correctly. I had already fixed this issue but I didn't push the commits to GitHub. I'll be back in a week and I'll do so

**Comment by marthin88** [comment]
Ok @Auties00. thanks for great project do you have here.

**Comment by Auties00** [comment]
> Ok @Auties00. thanks for great project do you have here.

Thanks :)

**Comment by Auties00** [comment]
Hello, I'm back. I'll fix the issue asap

**Comment by Auties00** [comment]
Fixed btw
