### ISSUE TITLE
Error after login: java.lang.NumberFormatException: For input string

### ISSUE THREAD

**Issue by brunoaduarte** [Auties00/WhatsappWeb4j#55]
```
package com.test.wsclientnew;

import org.springframework.boot.autoconfigure.SpringBootApplication;

import it.auties.whatsapp4j.whatsapp.WhatsappAPI;

@SpringBootApplication
public class WsclientNewApplication {

	public static void main(String[] args) {
		
		System.out.println("STARTING...");
		
		WhatsappAPI api = new WhatsappAPI();
		api.registerListener(new WsClientWhatsappListener());
		api.connect();
		
	}

}

```

```
STARTING...
<DISPLAY QR CODE AND LINK WITH DEVICE>
Connected :)

Nov 10, 2021 3:38:27 AM org.glassfish.tyrus.core.AnnotatedEndpoint callMethod
INFO: Exception thrown from onError method public void it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.onError(java.lang.Throwable).
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553)
        at org.glassfish.tyrus.core.AnnotatedEndpoint.onError(AnnotatedEndpoint.java:583)
        at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
        at org.glassfish.tyrus.core.AnnotatedEndpoint.access$100(AnnotatedEndpoint.java:66)
        at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652)
        at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:559)
        at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:800)
        at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
        at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
        at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
        at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:248)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:181)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:121)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:99)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.RuntimeException: An uncaught exception was thrown during the WebSocket lifecycle
        at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.onError(WhatsappWebSocket.java:236)
        ... 33 more
Caused by: java.lang.NumberFormatException: For input string: "64092211200"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:660)
        at java.base/java.lang.Integer.parseInt(Integer.java:778)
        at java.base/java.util.Optional.map(Optional.java:260)
        at it.auties.whatsapp4j.response.model.json.JsonResponse.getInteger(JsonResponse.java:76)
        at it.auties.whatsapp4j.protobuf.chat.Chat.fromAttributes(Chat.java:142)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at it.auties.whatsapp4j.manager.WhatsappDataManager.parseChats(WhatsappDataManager.java:548)
        at it.auties.whatsapp4j.manager.WhatsappDataManager.parseResponse(WhatsappDataManager.java:470)
        at it.auties.whatsapp4j.manager.WhatsappDataManager.digestWhatsappNode(WhatsappDataManager.java:270)
        at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.onBinary(WhatsappWebSocket.java:231)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553)
        ... 26 more
```

**Comment by Auties00** [comment]
> ```
> package com.test.wsclientnew;
> 
> import org.springframework.boot.autoconfigure.SpringBootApplication;
> 
> import it.auties.whatsapp4j.whatsapp.WhatsappAPI;
> 
> @SpringBootApplication
> public class WsclientNewApplication {
> 
> 	public static void main(String[] args) {
> 		
> 		System.out.println("STARTING...");
> 		
> 		WhatsappAPI api = new WhatsappAPI();
> 		api.registerListener(new WsClientWhatsappListener());
> 		api.connect();
> 		
> 	}
> 
> }
> ```
> 
> ```
> STARTING...
> <DISPLAY QR CODE AND LINK WITH DEVICE>
> Connected :)
> 
> Nov 10, 2021 3:38:27 AM org.glassfish.tyrus.core.AnnotatedEndpoint callMethod
> INFO: Exception thrown from onError method public void it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.onError(java.lang.Throwable).
> java.lang.reflect.InvocationTargetException
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
>         at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553)
>         at org.glassfish.tyrus.core.AnnotatedEndpoint.onError(AnnotatedEndpoint.java:583)
>         at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
>         at org.glassfish.tyrus.core.AnnotatedEndpoint.access$100(AnnotatedEndpoint.java:66)
>         at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652)
>         at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:559)
>         at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:800)
>         at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
>         at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
>         at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
>         at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725)
>         at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
>         at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
>         at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
>         at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
>         at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:248)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:181)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:121)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:99)
>         at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
>         at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
>         at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
>         at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
>         at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
>         at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
>         at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
>         at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
>         at java.base/java.lang.Thread.run(Thread.java:831)
> Caused by: java.lang.RuntimeException: An uncaught exception was thrown during the WebSocket lifecycle
>         at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.onError(WhatsappWebSocket.java:236)
>         ... 33 more
> Caused by: java.lang.NumberFormatException: For input string: "64092211200"
>         at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
>         at java.base/java.lang.Integer.parseInt(Integer.java:660)
>         at java.base/java.lang.Integer.parseInt(Integer.java:778)
>         at java.base/java.util.Optional.map(Optional.java:260)
>         at it.auties.whatsapp4j.response.model.json.JsonResponse.getInteger(JsonResponse.java:76)
>         at it.auties.whatsapp4j.protobuf.chat.Chat.fromAttributes(Chat.java:142)
>         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
>         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
>         at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
>         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
>         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
>         at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
>         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
>         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
>         at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
>         at it.auties.whatsapp4j.manager.WhatsappDataManager.parseChats(WhatsappDataManager.java:548)
>         at it.auties.whatsapp4j.manager.WhatsappDataManager.parseResponse(WhatsappDataManager.java:470)
>         at it.auties.whatsapp4j.manager.WhatsappDataManager.digestWhatsappNode(WhatsappDataManager.java:270)
>         at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.onBinary(WhatsappWebSocket.java:231)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
>         at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553)
>         ... 26 more
> ```

This bug is already fixed in the latest version, I just have to publish it. It will be available this afternoon
