### ISSUE TITLE
Chat querying does not work as expected

### ISSUE THREAD

**Issue by DevOFVictory** [Auties00/WhatsappWeb4j#72]
When using 
```java
Chat chat = api.queryChat("my_phone_number@s.whatsapp.net").get().data();
```
I only get this exception:
```
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot convert Node[description=response, attrs={duplicate=true, type=chat, status=750982}, content=null] to it.auties.whatsapp4j.response.impl.binary.ChatResponse as an exception occurred while initializing said class
at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
```

**Comment by Auties00** [comment]
> When using
> 
> ```java
> Chat chat = api.queryChat("my_phone_number@s.whatsapp.net").get().data();
> ```
> 
> I only get this exception:
> 
> ```
> java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot convert Node[description=response, attrs={duplicate=true, type=chat, status=750982}, content=null] to it.auties.whatsapp4j.response.impl.binary.ChatResponse as an exception occurred while initializing said class
> at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
> at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
> ```

Isn't there a caused block?

**Comment by DevOFVictory** [comment]
Oh, sorry,
here is the caused block:
```
Caused by: java.lang.IllegalArgumentException: Cannot convert Node[description=response, attrs={duplicate=true, type=chat, status=750982}, content=null] to it.auties.whatsapp4j.response.impl.binary.ChatResponse as an exception occurred while initializing said class
        at it.auties.whatsapp4j.response.model.binary.BinaryResponse.toModel(BinaryResponse.java:33)
        at it.auties.whatsapp4j.request.model.Request.lambda$complete$0(Request.java:105)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at it.auties.whatsapp4j.response.model.binary.BinaryResponse.toModel(BinaryResponse.java:31)
        ... 8 more
Caused by: java.lang.IllegalArgumentException: WhatsappAPI: Cannot parse Node[description=response, attrs={duplicate=true, type=chat, status=750982}, content=null] as Chat
        at it.auties.whatsapp4j.response.impl.binary.ChatResponse.lambda$parseResponse$1(ChatResponse.java:36)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at it.auties.whatsapp4j.response.impl.binary.ChatResponse.parseResponse(ChatResponse.java:36)
        at it.auties.whatsapp4j.response.impl.binary.ChatResponse.parseResponse(ChatResponse.java:12)
        at it.auties.whatsapp4j.response.model.binary.BinaryResponseModel.<init>(BinaryResponseModel.java:30)
        at it.auties.whatsapp4j.response.impl.binary.ChatResponse.<init>(ChatResponse.java:20)
        ... 14 more     
```

**Comment by Auties00** [comment]
> Oh, sorry, here is the caused block:
> 
> ```
> Caused by: java.lang.IllegalArgumentException: Cannot convert Node[description=response, attrs={duplicate=true, type=chat, status=750982}, content=null] to it.auties.whatsapp4j.response.impl.binary.ChatResponse as an exception occurred while initializing said class
>         at it.auties.whatsapp4j.response.model.binary.BinaryResponse.toModel(BinaryResponse.java:33)
>         at it.auties.whatsapp4j.request.model.Request.lambda$complete$0(Request.java:105)
>         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
>         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
>         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
>         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
>         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
>         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
>         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
> Caused by: java.lang.reflect.InvocationTargetException
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
>         at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
>         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
>         at it.auties.whatsapp4j.response.model.binary.BinaryResponse.toModel(BinaryResponse.java:31)
>         ... 8 more
> Caused by: java.lang.IllegalArgumentException: WhatsappAPI: Cannot parse Node[description=response, attrs={duplicate=true, type=chat, status=750982}, content=null] as Chat
>         at it.auties.whatsapp4j.response.impl.binary.ChatResponse.lambda$parseResponse$1(ChatResponse.java:36)
>         at java.base/java.util.Optional.orElseThrow(Optional.java:403)
>         at it.auties.whatsapp4j.response.impl.binary.ChatResponse.parseResponse(ChatResponse.java:36)
>         at it.auties.whatsapp4j.response.impl.binary.ChatResponse.parseResponse(ChatResponse.java:12)
>         at it.auties.whatsapp4j.response.model.binary.BinaryResponseModel.<init>(BinaryResponseModel.java:30)
>         at it.auties.whatsapp4j.response.impl.binary.ChatResponse.<init>(ChatResponse.java:20)
>         ... 14 more     
> ```

Should be fixed in latest version

**Comment by DevOFVictory** [comment]
No, its not :(

**Comment by DevOFVictory** [comment]
In version 2.2.7 the error is now
```
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot convert Node[description=response, attrs={duplicate=true, type=chat, status=750982}, content=null] to it.auties.whatsapp4j.response.impl.binary.ChatResponse as an exception occurred while initializing said class
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        at de.devofvictory.wwb.commands.SuggestCommand.performCommand(SuggestCommand.java:36)
        at de.devofvictory.wwb.utils.CommandManager.performChatCommand(CommandManager.java:124)
        at de.devofvictory.wwb.listeners.ChatCommandListener.onNewMessage(ChatCommandListener.java:37)
        at it.auties.whatsapp4j.manager.WhatsappDataManager.lambda$broadcastMessage$35(WhatsappDataManager.java:589)
        at it.auties.whatsapp4j.manager.WhatsappDataManager.lambda$callListeners$8(WhatsappDataManager.java:251)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Cannot convert Node[description=response, attrs={duplicate=true, type=chat, status=750982}, content=null] to it.auties.whatsapp4j.response.impl.binary.ChatResponse as an exception occurred while initializing said class
        at it.auties.whatsapp4j.response.model.binary.BinaryResponse.toModel(BinaryResponse.java:33)
        at it.auties.whatsapp4j.request.model.Request.lambda$complete$0(Request.java:105)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at it.auties.whatsapp4j.response.model.binary.BinaryResponse.toModel(BinaryResponse.java:31)
        ... 8 more
Caused by: java.lang.IllegalArgumentException: WhatsappAPI: Cannot parse Node[description=response, attrs={duplicate=true, type=chat, status=750982}, content=null] as Chat
        at it.auties.whatsapp4j.response.impl.binary.ChatResponse.lambda$parseResponse$1(ChatResponse.java:36)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at it.auties.whatsapp4j.response.impl.binary.ChatResponse.parseResponse(ChatResponse.java:36)
        at it.auties.whatsapp4j.response.impl.binary.ChatResponse.parseResponse(ChatResponse.java:12)
        at it.auties.whatsapp4j.response.model.binary.BinaryResponseModel.<init>(BinaryResponseModel.java:30)
        at it.auties.whatsapp4j.response.impl.binary.ChatResponse.<init>(ChatResponse.java:20)
        ... 14 more
```
