### ISSUE TITLE
Connection times out

### ISSUE THREAD

**Issue by DevOFVictory** [Auties00/WhatsappWeb4j#81]
After a specific time the whatsapp client disconnects and I get this error in console:
```java
Exception in thread "ForkJoinPool.commonPool-worker-98" java.lang.IllegalStateException: The connection has been closed.                     
        at org.glassfish.tyrus.core.TyrusSession.checkConnectionState(TyrusSession.java:513)                                                 
        at org.glassfish.tyrus.core.TyrusSession.getAsyncRemote(TyrusSession.java:183)                                                       
        at it.auties.whatsapp4j.request.model.JsonRequest.send(JsonRequest.java:59)                                                          
        at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.createMediaConnection(WhatsappWebSocket.java:401)                        
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)                                    
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)                                                         
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)                                        
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)                                                          
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)                                                     
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Auties00** [comment]
> After a specific time the whatsapp client disconnects and I get this error in console:
> 
> ```java
> Exception in thread "ForkJoinPool.commonPool-worker-98" java.lang.IllegalStateException: The connection has been closed.                     
>         at org.glassfish.tyrus.core.TyrusSession.checkConnectionState(TyrusSession.java:513)                                                 
>         at org.glassfish.tyrus.core.TyrusSession.getAsyncRemote(TyrusSession.java:183)                                                       
>         at it.auties.whatsapp4j.request.model.JsonRequest.send(JsonRequest.java:59)                                                          
>         at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.createMediaConnection(WhatsappWebSocket.java:401)                        
>         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)                                    
>         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)                                                         
>         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)                                        
>         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)                                                          
>         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)                                                     
>         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
> ```

Have you tried version 2.2.4?

**Comment by DevOFVictory** [comment]
Oh, my bad. I hadn't updated yet. Now it seems to work.

**Comment by DevOFVictory** [comment]
Still getting the same exception after specific time without the device disconnecting from the internet.

**Comment by Auties00** [comment]
> Still getting the same exception after specific time without the device disconnecting from the internet.

Can you try 2.2.7?

**Comment by DevOFVictory** [comment]
No disconnect after 2 hours.
Continue waiting...

**Comment by Auties00** [comment]
> No disconnect after 2 hours. Continue waiting...

Any news?

**Comment by DevOFVictory** [comment]
It seems to be working now. Many thanks!

**Comment by DevOFVictory** [comment]
Nevermind, got the same exception again two times in the last 2 days :(

**Comment by mircoker** [comment]
Same problem

**Comment by mircoker** [comment]
But I have not yet checked whether this affects the work or not. Because the reconnect is set to true.

**Comment by mircoker** [comment]
Yes, the connection is interrupted, close event does not come, and there is no reconnection

**Comment by Auties00** [comment]
Fixed with md
